from __future__ import annotations

from typing import Any

from app.rules.catalog_loader import load_catalogs


def _slug(value: Any) -> str:
    return str(value or "").strip().lower().replace(" ", "_")


PHB_CLASS_KEYS: tuple[str, ...] = (
    "barbarian",
    "bard",
    "cleric",
    "druid",
    "fighter",
    "monk",
    "paladin",
    "ranger",
    "rogue",
    "sorcerer",
    "warlock",
    "wizard",
)


PHB_RACE_KEYS: tuple[str, ...] = (
    "dragonborn",
    "dwarf",
    "elf",
    "gnome",
    "half_elf",
    "half_orc",
    "halfling",
    "human",
    "tiefling",
)


BASE_CLASS_CATALOG: list[dict[str, Any]] = [
    {
        "key": "barbarian",
        "name": "Barbarian",
        "name_ru": "Варвар",
        "source": "PHB",
        "description_ru": "Неистовый воин, полагающийся на ярость, стойкость и грубую силу.",
        "hit_die": 12,
        "primary_abilities": ["str"],
        "saving_throws": ["str", "con"],
        "proficiencies": {
            "armor": ["light", "medium", "shields"],
            "weapons": ["simple", "martial"],
            "tools": [],
            "skills_choose": {
                "count": 2,
                "from": ["athletics", "intimidation", "nature", "perception", "survival", "animal_handling"],
            },
        },
        "skill_choices": {},
        "starting_equipment": [
            {
                "key": "phb_barbarian_starting_equipment",
                "name_ru": "Стартовое снаряжение варвара",
                "summary_ru": "TODO: PHB equipment choices",
            }
        ],
        "features_by_level": {
            1: [
                {"key": "rage", "name_ru": "Ярость", "summary_ru": "В бою усиливает урон и выживаемость.", "mechanics": {}},
                {"key": "unarmored_defense", "name_ru": "Защита без доспехов", "summary_ru": "КД рассчитывается от Телосложения и Ловкости.", "mechanics": {}},
            ],
            2: [
                {"key": "reckless_attack", "name_ru": "Безрассудная атака", "summary_ru": "Можно атаковать агрессивно, повышая шанс попадания ценой защиты.", "mechanics": {}},
                {"key": "danger_sense", "name_ru": "Чувство опасности", "summary_ru": "Лучше избегает видимых угроз и ловушек.", "mechanics": {}},
            ],
            3: [
                {"key": "primal_path", "name_ru": "Путь дикости", "summary_ru": "Выбор подкласса варвара.", "mechanics": {"type": "subclass_choice"}},
            ],
            4: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            5: [
                {"key": "extra_attack", "name_ru": "Дополнительная атака", "summary_ru": "Совершает больше атак действием.", "mechanics": {}},
                {"key": "fast_movement", "name_ru": "Быстрое передвижение", "summary_ru": "Увеличивает скорость передвижения.", "mechanics": {}},
            ],
            6: [{"key": "path_feature_6", "name_ru": "Особенность пути (6)", "summary_ru": "Классовая особенность выбранного пути на 6 уровне.", "mechanics": {}}],
            7: [{"key": "feral_instinct", "name_ru": "Звериный инстинкт", "summary_ru": "Быстрее реагирует на начало схватки.", "mechanics": {}}],
            8: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            9: [{"key": "brutal_critical_1", "name_ru": "Жестокий критический удар (1)", "summary_ru": "Критические удары наносят больше урона.", "mechanics": {}}],
            10: [{"key": "path_feature_10", "name_ru": "Особенность пути (10)", "summary_ru": "Классовая особенность выбранного пути на 10 уровне.", "mechanics": {}}],
            11: [{"key": "relentless_rage", "name_ru": "Неукротимая ярость", "summary_ru": "Может удержаться на ногах после тяжёлого удара.", "mechanics": {}}],
            12: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            13: [{"key": "brutal_critical_2", "name_ru": "Жестокий критический удар (2)", "summary_ru": "Критические удары становятся ещё опаснее.", "mechanics": {}}],
            14: [{"key": "path_feature_14", "name_ru": "Особенность пути (14)", "summary_ru": "Классовая особенность выбранного пути на 14 уровне.", "mechanics": {}}],
            15: [{"key": "persistent_rage", "name_ru": "Постоянная ярость", "summary_ru": "Ярость удерживается дольше в сражении.", "mechanics": {}}],
            16: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            17: [{"key": "brutal_critical_3", "name_ru": "Жестокий критический удар (3)", "summary_ru": "Максимальная ступень усиления критических ударов.", "mechanics": {}}],
            18: [{"key": "indomitable_might", "name_ru": "Несокрушимая мощь", "summary_ru": "Чистая сила помогает в проверках даже при плохом броске.", "mechanics": {}}],
            19: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            20: [{"key": "primal_champion", "name_ru": "Первобытный чемпион", "summary_ru": "Пик физической мощи и выносливости варвара.", "mechanics": {}}],
        },
        "subclasses": [
            {
                "key": "berserker",
                "name_ru": "Путь берсерка",
                "features_by_level": {
                    3: [{"key": "frenzy", "name_ru": "Исступление", "summary_ru": "В ярости сражается с предельной агрессией.", "mechanics": {}}],
                    6: [{"key": "mindless_rage", "name_ru": "Безумная ярость", "summary_ru": "Ярость помогает игнорировать ментальные помехи.", "mechanics": {}}],
                    10: [{"key": "intimidating_presence", "name_ru": "Пугающее присутствие", "summary_ru": "Давит на врагов одним присутствием.", "mechanics": {}}],
                    14: [{"key": "retaliation", "name_ru": "Возмездие", "summary_ru": "Отвечает ударом на вражескую атаку.", "mechanics": {}}],
                },
            },
            {
                "key": "totem_warrior",
                "name_ru": "Путь тотемного воина",
                "features_by_level": {
                    3: [
                        {"key": "spirit_seeker", "name_ru": "Искатель духов", "summary_ru": "Осваивает ритуалы общения с духами природы.", "mechanics": {}},
                        {"key": "totem_spirit", "name_ru": "Дух тотема", "summary_ru": "Выбирает духа-покровителя, меняющего стиль боя.", "mechanics": {}},
                    ],
                    6: [{"key": "aspect_of_beast", "name_ru": "Аспект зверя", "summary_ru": "Получает дополнительную особенность выбранного тотема.", "mechanics": {}}],
                    10: [{"key": "commune_with_nature", "name_ru": "Единение с природой", "summary_ru": "Лучше чувствует окружающую местность и духов.", "mechanics": {}}],
                    14: [{"key": "totemic_attunement", "name_ru": "Тотемное единение", "summary_ru": "Высшая форма связи с тотемом в бою.", "mechanics": {}}],
                },
            },
        ],
        "spellcasting": {},
        "spell_lists": {},
        "tags": [],
    },
    {"key": "bard", "name": "Bard", "name_ru": "Бард", "source": "PHB", "description_ru": "", "hit_die": 8, "primary_abilities": [], "saving_throws": [], "proficiencies": {}, "skill_choices": {}, "starting_equipment": [], "features_by_level": {}, "subclasses": [], "spellcasting": {}, "spell_lists": {}, "tags": []},
    {"key": "cleric", "name": "Cleric", "name_ru": "Жрец", "source": "PHB", "description_ru": "", "hit_die": 8, "primary_abilities": [], "saving_throws": [], "proficiencies": {}, "skill_choices": {}, "starting_equipment": [], "features_by_level": {}, "subclasses": [], "spellcasting": {}, "spell_lists": {}, "tags": []},
    {"key": "druid", "name": "Druid", "name_ru": "Друид", "source": "PHB", "description_ru": "", "hit_die": 8, "primary_abilities": [], "saving_throws": [], "proficiencies": {}, "skill_choices": {}, "starting_equipment": [], "features_by_level": {}, "subclasses": [], "spellcasting": {}, "spell_lists": {}, "tags": []},
    {"key": "fighter", "name": "Fighter", "name_ru": "Воин", "source": "PHB", "description_ru": "", "hit_die": 10, "primary_abilities": [], "saving_throws": [], "proficiencies": {}, "skill_choices": {}, "starting_equipment": [], "features_by_level": {}, "subclasses": [], "spellcasting": {}, "spell_lists": {}, "tags": []},
    {"key": "monk", "name": "Monk", "name_ru": "Монах", "source": "PHB", "description_ru": "", "hit_die": 8, "primary_abilities": [], "saving_throws": [], "proficiencies": {}, "skill_choices": {}, "starting_equipment": [], "features_by_level": {}, "subclasses": [], "spellcasting": {}, "spell_lists": {}, "tags": []},
    {"key": "paladin", "name": "Paladin", "name_ru": "Паладин", "source": "PHB", "description_ru": "", "hit_die": 10, "primary_abilities": [], "saving_throws": [], "proficiencies": {}, "skill_choices": {}, "starting_equipment": [], "features_by_level": {}, "subclasses": [], "spellcasting": {}, "spell_lists": {}, "tags": []},
    {"key": "ranger", "name": "Ranger", "name_ru": "Следопыт", "source": "PHB", "description_ru": "", "hit_die": 10, "primary_abilities": [], "saving_throws": [], "proficiencies": {}, "skill_choices": {}, "starting_equipment": [], "features_by_level": {}, "subclasses": [], "spellcasting": {}, "spell_lists": {}, "tags": []},
    {"key": "rogue", "name": "Rogue", "name_ru": "Плут", "source": "PHB", "description_ru": "", "hit_die": 8, "primary_abilities": [], "saving_throws": [], "proficiencies": {}, "skill_choices": {}, "starting_equipment": [], "features_by_level": {}, "subclasses": [], "spellcasting": {}, "spell_lists": {}, "tags": []},
    {"key": "sorcerer", "name": "Sorcerer", "name_ru": "Чародей", "source": "PHB", "description_ru": "", "hit_die": 6, "primary_abilities": [], "saving_throws": [], "proficiencies": {}, "skill_choices": {}, "starting_equipment": [], "features_by_level": {}, "subclasses": [], "spellcasting": {}, "spell_lists": {}, "tags": []},
    {"key": "warlock", "name": "Warlock", "name_ru": "Колдун", "source": "PHB", "description_ru": "", "hit_die": 8, "primary_abilities": [], "saving_throws": [], "proficiencies": {}, "skill_choices": {}, "starting_equipment": [], "features_by_level": {}, "subclasses": [], "spellcasting": {}, "spell_lists": {}, "tags": []},
    {"key": "wizard", "name": "Wizard", "name_ru": "Волшебник", "source": "PHB", "description_ru": "", "hit_die": 6, "primary_abilities": [], "saving_throws": [], "proficiencies": {}, "skill_choices": {}, "starting_equipment": [], "features_by_level": {}, "subclasses": [], "spellcasting": {}, "spell_lists": {}, "tags": []},
    {"key": "artificer", "name": "Artificer", "name_ru": "Изобретатель", "source": "TCE", "description_ru": "", "hit_die": 8, "primary_abilities": [], "saving_throws": [], "proficiencies": {}, "skill_choices": {}, "starting_equipment": [], "features_by_level": {}, "subclasses": [], "spellcasting": {}, "spell_lists": {}, "tags": []},
    # Legacy compatibility
    {"key": "mage", "name": "Mage", "name_ru": "Маг", "source": "legacy", "description_ru": "", "hit_die": 6, "primary_abilities": [], "saving_throws": [], "proficiencies": {}, "skill_choices": {}, "starting_equipment": [], "features_by_level": {}, "subclasses": [], "spellcasting": {}, "spell_lists": {}, "tags": []},
]


BASE_RACE_CATALOG: list[dict[str, Any]] = [
    {
        "key": "human",
        "name": "Human",
        "name_ru": "Человек",
        "source": "PHB",
        "description_ru": "Универсальный и адаптивный народ, встречающийся по всему миру.",
        "asi": [
            {"stat": "str", "bonus": 1},
            {"stat": "dex", "bonus": 1},
            {"stat": "con", "bonus": 1},
            {"stat": "int", "bonus": 1},
            {"stat": "wis", "bonus": 1},
            {"stat": "cha", "bonus": 1},
        ],
        "age": {},
        "alignment": "",
        "size": "medium",
        "speed_ft": 30,
        "speed_notes_ru": "",
        "languages": ["common"],
        "traits": [
            {
                "key": "extra_language",
                "name_ru": "Дополнительный язык",
                "summary_ru": "Вы знаете ещё один язык на выбор.",
                "mechanics": {"type": "choose_language", "count": 1},
            }
        ],
        "subraces": [
            {
                "key": "variant_human",
                "name_ru": "Человек (вариант)",
                "asi": [],
                "traits": [
                    {
                        "key": "variant_asi",
                        "name_ru": "Вариативные характеристики",
                        "summary_ru": "+1 к двум характеристикам на выбор.",
                        "mechanics": {"type": "choose_asi", "choices": 2, "bonus": 1},
                    },
                    {
                        "key": "variant_skill",
                        "name_ru": "Вариативный навык",
                        "summary_ru": "Владение одним навыком на выбор.",
                        "mechanics": {"type": "choose_skill_proficiency", "count": 1},
                    },
                    {
                        "key": "variant_feat",
                        "name_ru": "Вариативная черта",
                        "summary_ru": "Одна черта на выбор.",
                        "mechanics": {"type": "choose_feat", "count": 1},
                    },
                    {
                        "key": "extra_language",
                        "name_ru": "Дополнительный язык",
                        "summary_ru": "Вы знаете ещё один язык на выбор.",
                        "mechanics": {"type": "choose_language", "count": 1},
                    },
                ],
            }
        ],
        "tags": [],
    },
    {
        "key": "aarakocra",
        "name": "Aarakocra",
        "name_ru": "Ааракокра",
        "source": "EEPC",
        "description_ru": "Крылатый народ с высокой мобильностью, обычно доступный по согласованию с мастером.",
        "asi": [{"stat": "dex", "bonus": 2}, {"stat": "wis", "bonus": 1}],
        "age": {},
        "alignment": "",
        "size": "medium",
        "speed_ft": 25,
        "speed_notes_ru": "",
        "languages": ["common", "auran", "aarakocra"],
        "traits": [
            {
                "key": "flight_aarakocra",
                "name_ru": "Полёт",
                "summary_ru": "Скорость полёта 50 футов; не работает в среднем и тяжёлом доспехе.",
                "mechanics": {
                    "type": "fly_speed",
                    "speed_ft": 50,
                    "restriction": {"no_armor_categories": ["medium", "heavy"]},
                },
            },
            {
                "key": "claws",
                "name_ru": "Когти",
                "summary_ru": "Когти можно использовать как безоружную атаку 1d4 рубящего урона.",
                "mechanics": {
                    "type": "natural_weapon",
                    "name_ru": "Когти",
                    "damage_dice": "1d4",
                    "damage_type": "slashing",
                    "kind": "unarmed",
                },
            },
        ],
        "subraces": [],
        "notes_ru": "Обычно требует разрешения мастера; placeholder для будущих ограничений кампании.",
        "tags": [],
    },
    {
        "key": "genasi",
        "name": "Genasi",
        "name_ru": "Дженази",
        "source": "PotA",
        "description_ru": "Народ с наследием стихийных планов.",
        "asi": [{"stat": "con", "bonus": 2, "delta": 2}],
        "age": {},
        "alignment": "",
        "size": "medium",
        "speed_ft": 30,
        "speed_notes_ru": "",
        "languages": ["common", "primordial"],
        "traits": [],
        "subraces": [
            {
                "key": "air_genasi",
                "name_ru": "Дженази воздуха",
                "asi": [{"stat": "dex", "bonus": 1, "delta": 1}],
                "traits": [
                    {
                        "key": "unending_breath",
                        "name_ru": "Бесконечное дыхание",
                        "summary_ru": "Может задерживать дыхание неограниченно долго.",
                        "mechanics": {"type": "hold_breath_indefinitely"},
                    },
                    {
                        "key": "mingle_with_the_wind",
                        "name_ru": "Слияние с ветром",
                        "summary_ru": "Заклинание levitate 1/длительный отдых без материальных компонентов (Хар-ка: Телосложение).",
                        "mechanics": {
                            "type": "spell_grants",
                            "casting_ability": "con",
                            "grants": [
                                {
                                    "kind": "spell",
                                    "spell": "levitate",
                                    "min_level": 1,
                                    "uses": "per_long_rest",
                                    "uses_max": 1,
                                    "material_components_required": False,
                                }
                            ],
                        },
                    },
                ],
            },
            {
                "key": "earth_genasi",
                "name_ru": "Дженази земли",
                "asi": [{"stat": "str", "bonus": 1, "delta": 1}],
                "traits": [
                    {
                        "key": "earth_walk",
                        "name_ru": "Шаг земли",
                        "summary_ru": "Игнорирует дополнительную стоимость труднопроходимой местности из земли и камня.",
                        "mechanics": {"type": "ignore_difficult_terrain_cost", "surfaces": ["earth", "stone"]},
                    },
                    {
                        "key": "merge_with_stone",
                        "name_ru": "Слияние с камнем",
                        "summary_ru": "Заклинание pass_without_trace 1/длительный отдых (Хар-ка: Телосложение).",
                        "mechanics": {
                            "type": "spell_grants",
                            "casting_ability": "con",
                            "grants": [{"kind": "spell", "spell": "pass_without_trace", "min_level": 1, "uses": "per_long_rest", "uses_max": 1}],
                        },
                    },
                ],
            },
            {
                "key": "fire_genasi",
                "name_ru": "Дженази огня",
                "asi": [{"stat": "int", "bonus": 1, "delta": 1}],
                "traits": [
                    {
                        "key": "darkvision_60_red",
                        "name_ru": "Тёмное зрение",
                        "summary_ru": "Тёмное зрение 60 футов; в темноте видит оттенки красного.",
                        "mechanics": {"type": "darkvision", "range_ft": 60, "note": "red_tones_only_in_darkness"},
                    },
                    {
                        "key": "fire_resistance",
                        "name_ru": "Сопротивление огню",
                        "summary_ru": "Сопротивление урону огнём.",
                        "mechanics": {"type": "damage_resistance", "damage_type": "fire"},
                    },
                    {
                        "key": "reach_to_the_blaze",
                        "name_ru": "Тяга к пламени",
                        "summary_ru": "Всегда знает produce_flame; с 3 уровня — burning_hands 1/длительный отдых (уровень 1, Хар-ка: Телосложение).",
                        "mechanics": {
                            "type": "spell_grants",
                            "casting_ability": "con",
                            "grants": [
                                {"kind": "cantrip", "spell": "produce_flame", "min_level": 1},
                                {
                                    "kind": "spell",
                                    "spell": "burning_hands",
                                    "spell_level": 1,
                                    "cast_as_level": 1,
                                    "min_level": 3,
                                    "uses": "per_long_rest",
                                    "uses_max": 1,
                                },
                            ],
                        },
                    },
                ],
            },
            {
                "key": "water_genasi",
                "name_ru": "Дженази воды",
                "asi": [{"stat": "wis", "bonus": 1, "delta": 1}],
                "traits": [
                    {
                        "key": "acid_resistance",
                        "name_ru": "Сопротивление кислоте",
                        "summary_ru": "Сопротивление урону кислотой.",
                        "mechanics": {"type": "damage_resistance", "damage_type": "acid"},
                    },
                    {
                        "key": "amphibious",
                        "name_ru": "Амфибия",
                        "summary_ru": "Может дышать воздухом и под водой.",
                        "mechanics": {"type": "amphibious"},
                    },
                    {
                        "key": "swim_speed",
                        "name_ru": "Скорость плавания",
                        "summary_ru": "Скорость плавания 30 футов.",
                        "mechanics": {"type": "swim_speed", "swim_speed_ft": 30},
                    },
                    {
                        "key": "call_to_the_wave",
                        "name_ru": "Зов волны",
                        "summary_ru": "Всегда знает shape_water; с 3 уровня — create_or_destroy_water 1/длительный отдых (уровень 2, Хар-ка: Телосложение).",
                        "mechanics": {
                            "type": "spell_grants",
                            "casting_ability": "con",
                            "grants": [
                                {"kind": "cantrip", "spell": "shape_water", "min_level": 1},
                                {
                                    "kind": "spell",
                                    "spell": "create_or_destroy_water",
                                    "spell_level": 1,
                                    "cast_as_level": 2,
                                    "min_level": 3,
                                    "uses": "per_long_rest",
                                    "uses_max": 1,
                                },
                            ],
                        },
                    },
                ],
            },
        ],
        "notes_ru": "Reference-каркас PotA; механики как placeholders.",
        "tags": [],
    },
    {
        "key": "goliath",
        "name": "Goliath",
        "name_ru": "Голиаф",
        "source": "VGM",
        "description_ru": "Высокогорный народ с выдающейся физической выносливостью.",
        "asi": [{"stat": "str", "bonus": 2}, {"stat": "con", "bonus": 1}],
        "age": {},
        "alignment": "",
        "size": "medium",
        "speed_ft": 30,
        "speed_notes_ru": "",
        "languages": ["common", "giant"],
        "traits": [
            {
                "key": "powerful_build",
                "name_ru": "Мощное телосложение",
                "summary_ru": "Считается на одну категорию размера больше при переноске, толкании, тяге и подъёме тяжестей.",
                "mechanics": {
                    "type": "powerful_build",
                    "applies_to": ["carrying_capacity", "push", "drag", "lift"],
                    "effective_size_delta": 1,
                },
            },
            {
                "key": "stone_endurance",
                "name_ru": "Каменная выносливость",
                "summary_ru": "Реакцией снижает получаемый урон на 1d12 + модификатор Телосложения (1/короткий или длительный отдых).",
                "mechanics": {
                    "type": "stone_endurance",
                    "roll": "1d12",
                    "add": "con_mod",
                    "trigger": "reaction_on_damage",
                    "uses": "per_short_or_long_rest",
                    "reduce_damage": True,
                },
            },
            {
                "key": "mountain_born",
                "name_ru": "Рождённый в горах",
                "summary_ru": "Сопротивление холоду, акклиматизация к высоте и адаптация к экстремальному холоду.",
                "mechanics": {
                    "type": "resistance",
                    "damage_type": "cold",
                    "altitude_acclimation_min_ft": 20000,
                    "climate_adaptation": "extreme_cold",
                },
            },
            {
                "key": "athletics_proficiency",
                "name_ru": "Прирождённый атлет",
                "summary_ru": "Владеет навыком Атлетика.",
                "mechanics": {"type": "skill_proficiency", "skill": "athletics"},
            },
        ],
        "subraces": [],
        "tags": [],
    },
    {
        "key": "aasimar",
        "name": "Aasimar",
        "name_ru": "Аасимар",
        "source": "VGM",
        "description_ru": "Потомки небесной крови с врождённым светом и целительной силой.",
        "asi": [{"stat": "cha", "bonus": 2}],
        "age": {},
        "alignment": "",
        "size": "medium",
        "speed_ft": 30,
        "speed_notes_ru": "",
        "languages": ["common", "celestial"],
        "traits": [
            {
                "key": "darkvision_60",
                "name_ru": "Тёмное зрение",
                "summary_ru": "Тёмное зрение 60 футов.",
                "mechanics": {"type": "darkvision", "range_ft": 60},
            },
            {
                "key": "celestial_resistance",
                "name_ru": "Небесная устойчивость",
                "summary_ru": "Сопротивление некротическому урону и урону излучением.",
                "mechanics": {"type": "damage_resistances", "damage_types": ["radiant", "necrotic"]},
            },
            {
                "key": "healing_hands",
                "name_ru": "Исцеляющие руки",
                "summary_ru": "Действием восстанавливает хиты в размере уровня персонажа (1/длительный отдых).",
                "mechanics": {"type": "healing_hands", "action_cost": "action", "heal_amount": "level", "uses": "per_long_rest", "uses_max": 1},
            },
            {
                "key": "light_cantrip",
                "name_ru": "Свет",
                "summary_ru": "Знает заговор light (базовая характеристика заклинаний — Харизма).",
                "mechanics": {"type": "spell_grants", "casting_ability": "cha", "grants": [{"kind": "cantrip", "spell": "light", "min_level": 1}]},
            },
        ],
        "subraces": [
            {
                "key": "aasimar_protector",
                "name_ru": "Аасимар-защитник",
                "asi": [{"stat": "wis", "bonus": 1}],
                "traits": [
                    {
                        "key": "radiant_soul",
                        "name_ru": "Сияющая душа",
                        "summary_ru": "С 3 уровня: действием на 1 минуту получает полёт 30 футов и 1 раз за ход добавляет к урону излучением величину уровня (1/длительный отдых).",
                        "mechanics": {
                            "type": "transformation",
                            "min_level": 3,
                            "action_cost": "action",
                            "duration_rounds": 10,
                            "uses": "per_long_rest",
                            "uses_max": 1,
                            "fly_speed_ft": 30,
                            "bonus_damage": {"type": "radiant", "amount": "level", "limit": "once_per_turn"},
                        },
                    }
                ],
            },
            {
                "key": "aasimar_scourge",
                "name_ru": "Аасимар-каратель",
                "asi": [{"stat": "con", "bonus": 1}],
                "traits": [
                    {
                        "key": "radiant_consumption",
                        "name_ru": "Лучистое поглощение",
                        "summary_ru": "С 3 уровня: действием на 1 минуту испускает свет и в конце хода наносит лучистый урон в ауре 10 футов (включая себя), а также 1 раз за ход добавляет к урону излучением величину уровня (1/длительный отдых).",
                        "mechanics": {
                            "type": "transformation",
                            "min_level": 3,
                            "action_cost": "action",
                            "duration_rounds": 10,
                            "uses": "per_long_rest",
                            "uses_max": 1,
                            "light_emission": {"bright_ft": 10, "dim_ft": 10},
                            "end_of_turn_aura_damage": {"type": "radiant", "radius_ft": 10, "amount": "ceil(level/2)", "targets": "self_and_creatures"},
                            "bonus_damage": {"type": "radiant", "amount": "level", "limit": "once_per_turn"},
                        },
                    }
                ],
            },
            {
                "key": "aasimar_fallen",
                "name_ru": "Падший аасимар",
                "asi": [{"stat": "str", "bonus": 1}],
                "traits": [
                    {
                        "key": "necrotic_shroud",
                        "name_ru": "Некротический покров",
                        "summary_ru": "С 3 уровня: действием на 1 минуту вызывает ужас в радиусе 10 футов (Спасбросок Харизмы, СЛ 8 + бонус мастерства + модификатор Харизмы) и 1 раз за ход добавляет к урону некротический урон, равный уровню (1/длительный отдых). Крылья не дают полёт.",
                        "mechanics": {
                            "type": "transformation",
                            "min_level": 3,
                            "action_cost": "action",
                            "duration_rounds": 10,
                            "uses": "per_long_rest",
                            "uses_max": 1,
                            "fear_on_transform": {
                                "radius_ft": 10,
                                "save_ability": "cha",
                                "dc_formula": "8 + proficiency_bonus + cha_mod",
                                "duration": "until_end_of_your_next_turn",
                            },
                            "bonus_damage": {"type": "necrotic", "amount": "level", "limit": "once_per_turn"},
                            "wings_grant_flight": False,
                        },
                    }
                ],
            },
        ],
        "notes_ru": "Смена разновидности обычно требует согласия Мастера.",
        "tags": [],
    },
    {
        "key": "vedalken",
        "name": "Vedalken",
        "name_ru": "Ведалкен",
        "source": "GGtR",
        "description_ru": "Рациональный народ исследователей и мастеров точности.",
        "asi": [{"stat": "int", "bonus": 2}, {"stat": "wis", "bonus": 1}],
        "age": {},
        "alignment": "",
        "size": "medium",
        "speed_ft": 30,
        "speed_notes_ru": "",
        "languages": ["common", "vedalken"],
        "traits": [
            {
                "key": "vedalken_dispassion",
                "name_ru": "Бесстрастие ведалкенов",
                "summary_ru": "Преимущество на спасброски Инт/Муд/Хар.",
                "mechanics": {"type": "saving_throw_advantage", "abilities": ["int", "wis", "cha"]},
            },
            {
                "key": "tireless_precision",
                "name_ru": "Неустанная скрупулёзность",
                "summary_ru": "Выбирает 1 навык из списка и 1 инструмент; добавляет 1d4 к проверкам с ними.",
                "mechanics": {
                    "type": "tireless_precision",
                    "choose_skill_from": ["performance", "history", "sleight_of_hand", "arcana", "medicine", "investigation"],
                    "choose_tool": True,
                    "bonus_die": "1d4",
                    "applies_to": ["ability_check"],
                },
            },
            {
                "key": "partially_amphibious",
                "name_ru": "Частично амфибия",
                "summary_ru": "Может дышать под водой до 1 часа, затем восстанавливает способность после длительного отдыха.",
                "mechanics": {"type": "breathe_underwater", "duration_seconds": 3600, "uses": "per_long_rest"},
            },
            {
                "key": "extra_language",
                "name_ru": "Дополнительный язык",
                "summary_ru": "Знает ещё один язык на выбор.",
                "mechanics": {"type": "choose_language", "count": 1},
            },
        ],
        "subraces": [],
        "notes_ru": "Источник: Guildmasters’ Guide to Ravnica; мировоззрение любое.",
        "tags": [],
    },
    {
        "key": "verdan",
        "name": "Verdan",
        "name_ru": "Вердан",
        "source": "AI",
        "description_ru": "Народ с подвижной природой и необычными ментальными способностями.",
        "asi": [{"stat": "cha", "bonus": 2}, {"stat": "con", "bonus": 1}],
        "age": {},
        "alignment": "",
        "size": "small",
        "speed_ft": 30,
        "speed_notes_ru": "",
        "languages": ["common", "goblin"],
        "traits": [
            {
                "key": "black_blood_healing",
                "name_ru": "Чёрная кровь: восстановление",
                "summary_ru": "При броске кости хитов на коротком отдыхе результат 1 или 2 можно перебросить и использовать новый.",
                "mechanics": {
                    "type": "hit_die_reroll",
                    "on_values": [1, 2],
                    "context": "short_rest_healing",
                    "use_new_result": True,
                },
            },
            {
                "key": "limited_telepathy",
                "name_ru": "Ограниченная телепатия",
                "summary_ru": "Телепатия на 30 футов с существами, которые понимают хотя бы один язык.",
                "mechanics": {
                    "type": "limited_telepathy",
                    "range_ft": 30,
                    "target_must_understand_at_least_one_language": True,
                },
            },
            {
                "key": "persuasive",
                "name_ru": "Убедительность",
                "summary_ru": "Владеет навыком Убеждение.",
                "mechanics": {"type": "skill_proficiency", "skill": "persuasion"},
            },
            {
                "key": "telepathic_insight",
                "name_ru": "Телепатическое чутьё",
                "summary_ru": "Преимущество на спасброски Мудрости и Харизмы.",
                "mechanics": {"type": "saving_throw_advantage", "abilities": ["wis", "cha"]},
            },
            {
                "key": "extra_language",
                "name_ru": "Дополнительный язык",
                "summary_ru": "Знает ещё один язык на выбор.",
                "mechanics": {"type": "choose_language", "count": 1},
            },
            {
                "key": "growth_spurt",
                "name_ru": "Скачок роста",
                "summary_ru": "На 5 уровне размер становится Средним.",
                "mechanics": {"type": "size_progression", "level_from": 5, "size": "medium"},
            },
        ],
        "subraces": [],
        "notes_ru": "Источник: Acquisition Incorporated. На 5 уровне размер становится Средним.",
        "tags": [],
    },
    {
        "key": "dragonborn",
        "name": "Dragonborn",
        "name_ru": "Драконорождённый",
        "source": "PHB",
        "description_ru": "Гордый народ с драконьей кровью, обладающий дыханием и стихийной стойкостью.",
        "asi": [{"stat": "str", "bonus": 2}, {"stat": "cha", "bonus": 1}],
        "age": {},
        "alignment": "",
        "size": "medium",
        "speed_ft": 30,
        "speed_notes_ru": "",
        "languages": ["common", "draconic"],
        "traits": [
            {
                "key": "draconic_ancestry",
                "name_ru": "Драконье наследие",
                "summary_ru": "Выберите тип дракона-наследия. Он определяет вид урона и форму оружия дыхания.",
                "mechanics": {
                    "type": "choose_draconic_ancestry",
                    "options": [
                        {"key": "white", "damage_type": "cold", "breath": {"shape": "cone", "cone_ft": 15, "save": "con"}},
                        {"key": "silver", "damage_type": "cold", "breath": {"shape": "cone", "cone_ft": 15, "save": "con"}},
                        {"key": "green", "damage_type": "poison", "breath": {"shape": "cone", "cone_ft": 15, "save": "con"}},
                        {
                            "key": "blue",
                            "damage_type": "lightning",
                            "breath": {"shape": "line", "line_ft": 30, "line_width_ft": 5, "save": "dex"},
                        },
                        {
                            "key": "bronze",
                            "damage_type": "lightning",
                            "breath": {"shape": "line", "line_ft": 30, "line_width_ft": 5, "save": "dex"},
                        },
                        {
                            "key": "black",
                            "damage_type": "acid",
                            "breath": {"shape": "line", "line_ft": 30, "line_width_ft": 5, "save": "dex"},
                        },
                        {
                            "key": "copper",
                            "damage_type": "acid",
                            "breath": {"shape": "line", "line_ft": 30, "line_width_ft": 5, "save": "dex"},
                        },
                        {"key": "red", "damage_type": "fire", "breath": {"shape": "cone", "cone_ft": 15, "save": "dex"}},
                        {"key": "gold", "damage_type": "fire", "breath": {"shape": "cone", "cone_ft": 15, "save": "dex"}},
                        {
                            "key": "brass",
                            "damage_type": "fire",
                            "breath": {"shape": "line", "line_ft": 30, "line_width_ft": 5, "save": "dex"},
                        },
                    ],
                },
            },
            {
                "key": "breath_weapon",
                "name_ru": "Оружие дыхания",
                "summary_ru": "Действием выдыхаете разрушительную энергию. Спасбросок: Сл = 8 + мод Телосложения + бонус мастерства. Урон 2к6, растёт с уровнем. Перезарядка: короткий/длительный отдых.",
                "mechanics": {
                    "type": "breath_weapon",
                    "action_cost": "action",
                    "dc_formula": "8 + con_mod + proficiency_bonus",
                    "damage_progression": [
                        {"level_from": 1, "dice": "2d6"},
                        {"level_from": 6, "dice": "3d6"},
                        {"level_from": 11, "dice": "4d6"},
                        {"level_from": 16, "dice": "5d6"},
                    ],
                    "recharge": "short_or_long_rest",
                    "damage_type_from": "draconic_ancestry",
                    "area_from": "draconic_ancestry",
                },
            },
            {
                "key": "damage_resistance",
                "name_ru": "Сопротивление урону",
                "summary_ru": "Вы получаете сопротивление урону того вида, который указан в вашем наследии драконов.",
                "mechanics": {"type": "damage_resistance", "damage_type_from": "draconic_ancestry"},
            },
        ],
        "subraces": [],
        "tags": [],
    },
    {
        "key": "dwarf",
        "name": "Dwarf",
        "name_ru": "Дварф",
        "source": "PHB",
        "description_ru": "Крепкий и выносливый народ, привыкший к подземным залам и камню.",
        "asi": [{"stat": "con", "bonus": 2}],
        "age": {},
        "alignment": "",
        "size": "medium",
        "speed_ft": 25,
        "speed_notes_ru": "Ношение тяжёлых доспехов не снижает скорость.",
        "languages": ["common", "dwarvish"],
        "traits": [
            {
                "key": "darkvision",
                "name_ru": "Тёмное зрение",
                "text_ru": "Видит в темноте на ограничённой дистанции.",
                "mechanics": {"type": "sense", "name": "darkvision", "range_ft": 60},
            },
            {
                "key": "dwarven_resilience",
                "name_ru": "Дварфская стойкость",
                "text_ru": "Устойчив к яду и лучше сопротивляется его эффектам.",
                "mechanics": {"saves_advantage": ["poison"], "resistances": ["poison"]},
            },
            {
                "key": "dwarven_combat_training",
                "name_ru": "Дварфская боевая выучка",
                "text_ru": "Обучен традиционному оружию дварфов.",
                "mechanics": {
                    "type": "proficiency",
                    "weapons": ["battleaxe", "handaxe", "light_hammer", "warhammer"],
                },
            },
            {
                "key": "tool_proficiency",
                "name_ru": "Владение инструментами",
                "text_ru": "Выбирает один ремесленный набор дварфов.",
                "mechanics": {"choose": 1, "from": ["smith_tools", "brewer_supplies", "mason_tools"]},
            },
            {
                "key": "stonecunning",
                "name_ru": "Знание камня",
                "text_ru": "Особо хорошо разбирается в истории и происхождении каменной кладки.",
                "mechanics": {"type": "skill_bonus", "skill": "history", "context": "stonework", "proficiency_multiplier": 2},
            },
        ],
        "subraces": [
            {
                "key": "hill_dwarf",
                "name_ru": "Холмовой дварф",
                "asi": [{"stat": "wis", "bonus": 1}],
                "traits": [
                    {
                        "key": "dwarven_toughness",
                        "name_ru": "Дварфская живучесть",
                        "text_ru": "Дополнительная живучесть увеличивает максимальные хиты.",
                        "mechanics": {"type": "hp_scaling", "base_bonus": 1, "per_level_bonus": 1},
                    }
                ],
            },
            {
                "key": "mountain_dwarf",
                "name_ru": "Горный дварф",
                "asi": [{"stat": "str", "bonus": 2}],
                "traits": [
                    {
                        "key": "dwarf_armor_training",
                        "name_ru": "Дварфская доспешная выучка",
                        "text_ru": "Владеет лёгкими и средними доспехами.",
                        "mechanics": {"type": "proficiency", "armor": ["light", "medium"]},
                    }
                ],
            },
        ],
        "tags": [],
    },
    {
        "key": "elf",
        "name": "Elf",
        "name_ru": "Эльф",
        "source": "PHB",
        "description_ru": "Изящный и долгоживущий народ с сильной связью с магией и природой.",
        "asi": [{"stat": "dex", "bonus": 2}],
        "age": {},
        "alignment": "",
        "size": "medium",
        "speed_ft": 30,
        "speed_notes_ru": "",
        "languages": ["common", "elvish"],
        "traits": [
            {
                "key": "darkvision_60",
                "name_ru": "Тёмное зрение",
                "text_ru": "Видит в темноте на 60 футов.",
                "mechanics": {"type": "sense", "name": "darkvision", "range_ft": 60},
            },
            {
                "key": "keen_senses",
                "name_ru": "Острое восприятие",
                "text_ru": "Обладает врождённой внимательностью к окружению.",
                "mechanics": {"type": "proficiency", "skills": ["perception"]},
            },
            {
                "key": "fey_ancestry",
                "name_ru": "Наследие фей",
                "text_ru": "Устойчив к очарованию и не поддаётся магическому сну.",
                "mechanics": {"saves_advantage": ["charmed"], "immunities": ["magic_sleep"]},
            },
            {
                "key": "trance",
                "name_ru": "Транс",
                "text_ru": "Отдыхает через медитацию, а не обычный сон.",
                "mechanics": {"type": "rest_override", "trance_hours": 4, "equivalent_rest_hours": 8},
            },
        ],
        "subraces": [
            {
                "key": "high_elf",
                "name_ru": "Высший эльф",
                "asi": [{"stat": "int", "bonus": 1}],
                "traits": [
                    {
                        "key": "elf_weapon_training",
                        "name_ru": "Эльфийская оружейная подготовка",
                        "text_ru": "Владеет традиционным оружием эльфов.",
                        "mechanics": {"type": "proficiency", "weapons": ["longsword", "shortsword", "shortbow", "longbow"]},
                    },
                    {
                        "key": "wizard_cantrip",
                        "name_ru": "Заговор мага",
                        "text_ru": "Выбирает один заговор из списка волшебника.",
                        "mechanics": {"type": "choice", "choose": 1, "from_list": "wizard_cantrips", "ability": "int"},
                    },
                    {
                        "key": "extra_language",
                        "name_ru": "Дополнительный язык",
                        "text_ru": "Знает ещё один язык по выбору.",
                        "mechanics": {"type": "choice", "choose": 1, "from": "any_language"},
                    },
                ],
            },
            {
                "key": "wood_elf",
                "name_ru": "Лесной эльф",
                "asi": [{"stat": "wis", "bonus": 1}],
                "speed_ft": 35,
                "traits": [
                    {
                        "key": "elf_weapon_training",
                        "name_ru": "Эльфийская оружейная подготовка",
                        "text_ru": "Владеет традиционным оружием эльфов.",
                        "mechanics": {"type": "proficiency", "weapons": ["longsword", "shortsword", "shortbow", "longbow"]},
                    },
                    {
                        "key": "mask_of_the_wild",
                        "name_ru": "Маска леса",
                        "text_ru": "Может скрываться даже при лёгком природном укрытии.",
                        "mechanics": {"type": "stealth_bonus", "condition": "light_natural_obscurement"},
                    },
                ],
            },
            {
                "key": "drow",
                "name_ru": "Тёмный эльф (Дроу)",
                "asi": [{"stat": "cha", "bonus": 1}],
                "traits": [
                    {
                        "key": "superior_darkvision_120",
                        "name_ru": "Усиленное тёмное зрение",
                        "text_ru": "Видит в темноте на 120 футов.",
                        "mechanics": {"type": "sense", "name": "darkvision", "range_ft": 120},
                    },
                    {
                        "key": "sunlight_sensitivity",
                        "name_ru": "Чувствительность к солнечному свету",
                        "text_ru": "Под прямым солнцем хуже атакует и замечает детали взглядом.",
                        "mechanics": {"disadvantage": ["attack_rolls_in_sunlight", "perception_vision_in_sunlight"]},
                    },
                    {
                        "key": "drow_magic",
                        "name_ru": "Магия дроу",
                        "text_ru": "По мере роста получает набор врождённых заклинаний.",
                        "mechanics": {
                            "ability": "cha",
                            "spells": [
                                {"spell_ref": "dancing_lights", "kind": "cantrip"},
                                {"spell_ref": "faerie_fire", "uses_per_day": 1, "min_level": 3},
                                {"spell_ref": "darkness", "uses_per_day": 1, "min_level": 5},
                            ],
                        },
                    },
                    {
                        "key": "drow_weapon_training",
                        "name_ru": "Оружейная подготовка дроу",
                        "text_ru": "Владеет фирменным оружием дроу.",
                        "mechanics": {"type": "proficiency", "weapons": ["rapier", "shortsword", "hand_crossbow"]},
                    },
                ],
            },
        ],
        "tags": [],
    },
    {
        "key": "gnome",
        "name": "Gnome",
        "name_ru": "Гном",
        "source": "PHB",
        "description_ru": "Любознательный и изобретательный малый народ с сильной тягой к знаниям.",
        "asi": [{"stat": "int", "bonus": 2}],
        "age": {},
        "alignment": "",
        "size": "small",
        "speed_ft": 25,
        "speed_notes_ru": "",
        "languages": ["common", "gnomish"],
        "traits": [
            {
                "key": "darkvision_60",
                "name_ru": "Тёмное зрение",
                "summary_ru": "Тёмное зрение 60 футов.",
                "mechanics": {"type": "darkvision", "range_ft": 60},
            },
            {
                "key": "gnome_cunning",
                "name_ru": "Гномья хитрость",
                "summary_ru": "Преимущество на спасброски Инт/Муд/Хар против магии.",
                "mechanics": {"type": "save_advantage", "vs": "magic", "stats": ["int", "wis", "cha"]},
            },
        ],
        "subraces": [
            {
                "key": "forest_gnome",
                "name_ru": "Лесной гном",
                "asi": [{"stat": "dex", "bonus": 1}],
                "traits": [
                    {
                        "key": "natural_illusionist",
                        "name_ru": "Природный иллюзионист",
                        "summary_ru": "Вы знаете заговор «малая иллюзия» (Интеллект).",
                        "mechanics": {"type": "learn_cantrip", "spell_key": "minor_illusion", "ability": "int"},
                    },
                    {
                        "key": "speak_with_small_beasts",
                        "name_ru": "Речь малых зверей",
                        "summary_ru": "Общение с маленькими зверями (простые идеи через звуки/жесты).",
                        "mechanics": {"type": "talk_with_small_beasts", "max_size": "small"},
                    },
                ],
            },
            {
                "key": "rock_gnome",
                "name_ru": "Скальный гном",
                "asi": [{"stat": "con", "bonus": 1}],
                "traits": [
                    {
                        "key": "artificers_lore",
                        "name_ru": "Знания изобретателя",
                        "summary_ru": "История: по магическим/алхимическим/технологическим объектам — удвоенный бонус мастерства.",
                        "mechanics": {"type": "expertise", "skill": "history", "when": "magical_alchemical_technological_objects"},
                    },
                    {
                        "key": "tinker",
                        "name_ru": "Жестянщик",
                        "summary_ru": "Владение инструментами жестянщика; можете создавать маленькие механические устройства.",
                        "mechanics": {
                            "type": "tinker",
                            "tool_proficiency": "tinkers_tools",
                            "build_time_hours": 1,
                            "materials_cost_gp": 1,
                            "max_active_devices": 3,
                            "device_hp": 1,
                            "device_ac": 5,
                            "duration_hours": 24,
                            "options": [
                                {"key": "clockwork_toy", "name_ru": "Заводная игрушка"},
                                {"key": "fire_starter", "name_ru": "Зажигалка"},
                                {"key": "music_box", "name_ru": "Музыкальная шкатулка"},
                            ],
                        },
                    },
                ],
            },
        ],
        "tags": [],
    },
    {
        "key": "half_elf",
        "name": "Half-Elf",
        "name_ru": "Полуэльф",
        "source": "PHB",
        "description_ru": "Народ на стыке двух миров, сочетающий эльфийское наследие и человеческую гибкость.",
        "asi": [{"stat": "cha", "bonus": 2}],
        "age": {},
        "alignment": "",
        "size": "medium",
        "speed_ft": 30,
        "speed_notes_ru": "",
        "languages": ["common", "elvish"],
        "traits": [
            {
                "key": "darkvision_60",
                "name_ru": "Тёмное зрение",
                "summary_ru": "Тёмное зрение 60 футов.",
                "mechanics": {"type": "darkvision", "range_ft": 60},
            },
            {
                "key": "fey_ancestry",
                "name_ru": "Наследие фей",
                "summary_ru": "Преимущество на спасброски от очарования, и вас нельзя магически усыпить.",
                "mechanics": {"type": "fey_ancestry"},
            },
            {
                "key": "half_elf_versatility_asi",
                "name_ru": "Гибкость характеристик",
                "summary_ru": "Две другие характеристики на ваш выбор увеличиваются на 1.",
                "mechanics": {"type": "choose_asi", "count": 2, "delta": 1, "exclude": ["cha"], "max_stat": 20},
            },
            {
                "key": "skill_versatility",
                "name_ru": "Гибкость навыков",
                "summary_ru": "Вы получаете владение двумя навыками на ваш выбор.",
                "mechanics": {"type": "choose_skill_proficiencies", "count": 2},
            },
            {
                "key": "extra_language",
                "name_ru": "Дополнительный язык",
                "summary_ru": "Дополнительный язык на ваш выбор.",
                "mechanics": {"type": "choose_language", "count": 1},
            },
        ],
        "subraces": [],
        "tags": [],
    },
    {
        "key": "half_orc",
        "name": "Half-Orc",
        "name_ru": "Полуорк",
        "source": "PHB",
        "description_ru": "Могучий и выносливый народ с яростной боевой натурой.",
        "asi": [{"stat": "str", "bonus": 2}, {"stat": "con", "bonus": 1}],
        "age": {},
        "alignment": "",
        "size": "medium",
        "speed_ft": 30,
        "speed_notes_ru": "",
        "languages": ["common", "orc"],
        "traits": [
            {
                "key": "darkvision_60",
                "name_ru": "Тёмное зрение",
                "summary_ru": "Тёмное зрение 60 футов.",
                "mechanics": {"type": "darkvision", "range_ft": 60},
            },
            {
                "key": "menacing",
                "name_ru": "Грозный вид",
                "summary_ru": "Вы владеете навыком Запугивание.",
                "mechanics": {"type": "skill_proficiency", "skill": "intimidation"},
            },
            {
                "key": "relentless_endurance",
                "name_ru": "Неукротимая стойкость",
                "summary_ru": "Если ваши хиты опустились до 0, но вы не убиты, вместо этого они опускаются до 1 (1/длительный отдых).",
                "mechanics": {"type": "relentless_endurance", "uses": "per_long_rest", "set_hp_to": 1},
            },
            {
                "key": "savage_attacks",
                "name_ru": "Свирепые атаки",
                "summary_ru": "При критическом попадании рукопашной атакой оружием добавляете одну кость урона оружия.",
                "mechanics": {"type": "savage_attacks", "extra_weapon_damage_die": 1, "trigger": "melee_weapon_crit"},
            },
        ],
        "subraces": [],
        "tags": [],
    },
    {
        "key": "halfling",
        "name": "Halfling",
        "name_ru": "Полурослик",
        "source": "PHB",
        "description_ru": "Невысокий и ловкий народ, ценящий удачу, смелость и скрытность.",
        "asi": [{"stat": "dex", "bonus": 2}],
        "age": {},
        "alignment": "",
        "size": "small",
        "speed_ft": 25,
        "speed_notes_ru": "",
        "languages": ["common", "halfling"],
        "traits": [
            {
                "key": "lucky",
                "name_ru": "Везучий",
                "summary_ru": "Перебрасывает d20 при выпадении 1 на атаке, проверке или спасброске.",
                "mechanics": {"type": "reroll_ones", "scope": ["attack", "check", "save"], "note": "PHB Lucky placeholder"},
            },
            {
                "key": "brave",
                "name_ru": "Храбрый",
                "summary_ru": "Имеет преимущество на спасброски от испуга.",
                "mechanics": {"type": "save_advantage", "vs": "frightened"},
            },
            {
                "key": "halfling_nimbleness",
                "name_ru": "Проворство полурослика",
                "summary_ru": "Может проходить через пространство существ большего размера.",
                "mechanics": {"type": "move_through_larger_creatures"},
            },
        ],
        "subraces": [
            {
                "key": "lightfoot",
                "name_ru": "Легконогий",
                "asi": [{"stat": "cha", "bonus": 1}],
                "traits": [
                    {
                        "key": "naturally_stealthy",
                        "name_ru": "Природная скрытность",
                        "summary_ru": "Может скрыться, если заслонён существом на 1 размер больше.",
                        "mechanics": {"type": "hide_with_larger_cover"},
                    }
                ],
            },
            {
                "key": "stout",
                "name_ru": "Коренастый",
                "asi": [{"stat": "con", "bonus": 1}],
                "traits": [
                    {
                        "key": "stout_resilience",
                        "name_ru": "Коренастая стойкость",
                        "summary_ru": "Преимущество на спасброски от яда и сопротивление урону ядом.",
                        "mechanics": {"type": "poison_resilience", "save_advantage": True, "damage_resistance": True},
                    }
                ],
            },
        ],
        "tags": [],
    },
    {
        "key": "tiefling",
        "name": "Tiefling",
        "name_ru": "Тифлинг",
        "source": "PHB",
        "description_ru": "Народ с инфернальным наследием, наделённый огненной стойкостью и врождённой магией.",
        "asi": [{"stat": "int", "bonus": 1}, {"stat": "cha", "bonus": 2}],
        "age": {},
        "alignment": "",
        "size": "medium",
        "speed_ft": 30,
        "speed_notes_ru": "",
        "languages": ["common", "infernal"],
        "traits": [
            {
                "key": "darkvision_60",
                "name_ru": "Тёмное зрение",
                "summary_ru": "Тёмное зрение 60 футов.",
                "mechanics": {"type": "darkvision", "range_ft": 60},
            },
            {
                "key": "hellish_resistance",
                "name_ru": "Адская стойкость",
                "summary_ru": "Сопротивление урону огнём.",
                "mechanics": {"type": "damage_resistance", "damage_type": "fire"},
            },
            {
                "key": "infernal_legacy",
                "name_ru": "Дьявольское наследие",
                "summary_ru": "Дьявольское наследие: заговор + 1/день заклинания на 3 и 5 уровнях (Харизма).",
                "mechanics": {
                    "type": "spell_grants",
                    "casting_ability": "cha",
                    "grants": [
                        {"kind": "cantrip", "spell": "thaumaturgy", "min_level": 1},
                        {
                            "kind": "spell",
                            "spell": "hellish_rebuke",
                            "spell_level": 2,
                            "min_level": 3,
                            "uses": "per_long_rest",
                            "uses_max": 1,
                        },
                        {
                            "kind": "spell",
                            "spell": "darkness",
                            "spell_level": 2,
                            "min_level": 5,
                            "uses": "per_long_rest",
                            "uses_max": 1,
                        },
                    ],
                },
            },
        ],
        "subraces": [],
        "tags": [],
    },
]


# External / dnd.su races (previously in app.rules.races_imported)
# NOTE: Most of these are placeholders (empty description/traits) and should be filled later.
EXTERNAL_RACE_CATALOG: list[dict[str, Any]] = [{'key': 'autognome',
  'name_ru': 'Автогном',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {
  "key": "bugbear",
  "name": "Bugbear",
  "name_ru": "Багбир",
  "source": "VGM",
  "description_ru": "Крупный гоблиноид-засадник: полагается на скрытность, ночные атаки и грубую силу.",
  "asi": [{"stat": "str", "bonus": 2}, {"stat": "dex", "bonus": 1}],
  "age": {},
  "alignment": "",
  "size": "medium",
  "speed_ft": 30,
  "speed_notes_ru": "",
  "languages": ["common", "goblin"],
  "traits": [
   {
    "key": "darkvision_60",
    "name_ru": "Тёмное зрение",
    "summary_ru": "Тёмное зрение 60 футов.",
    "mechanics": {"type": "darkvision", "range_ft": 60},
   },
   {
    "key": "long_limbed",
    "name_ru": "Длинные конечности",
    "summary_ru": "В свой ход рукопашные атаки имеют досягаемость +5 футов.",
    "mechanics": {"type": "reach_bonus", "bonus_ft": 5, "when": "your_turn_melee_attacks"},
   },
   {
    "key": "powerful_build",
    "name_ru": "Мощное телосложение",
    "summary_ru": "Считается на 1 размер больше для переноски/толкания/тяги/подъёма.",
    "mechanics": {
     "type": "powerful_build",
     "applies_to": ["carrying_capacity", "push", "drag", "lift"],
     "effective_size_delta": 1,
    },
   },
   {
    "key": "stealth_proficiency",
    "name_ru": "Скрытность",
    "summary_ru": "Владение навыком Скрытность.",
    "mechanics": {"type": "skill_proficiency", "skill": "stealth"},
   },
   {
    "key": "surprise_attack",
    "name_ru": "Внезапное нападение",
    "summary_ru": "Если цель застигнута врасплох и вы попали в первый ход боя — доп. 2d6 (1 раз за бой).",
    "mechanics": {
     "type": "surprise_attack",
     "extra_damage": "2d6",
     "limit": "once_per_combat",
     "trigger": "hit_on_first_turn_vs_surprised",
    },
   },
  ],
  "subraces": [],
  "tags": [],
 },
 {'key': 'centaur',
  'name_ru': 'Кентавр',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'changeling',
  'name_ru': 'Чейнджлинг',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'custom_lineage',
  'name_ru': 'Своё происхождение',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'dhampir',
  'name_ru': 'Дампир',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'fairy',
  'name_ru': 'Фэйри',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'firbolg',
  'name_ru': 'Фирболг',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'gith',
  'name_ru': 'Гит',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {
  "key": "goblin",
  "name": "Goblin",
  "name_ru": "Гоблин",
  "source": "VGM",
  "description_ru": "Малый гоблиноид: быстрый, ловкий и хитрый, выживает за счёт рефлексов и подлых приёмов.",
  "asi": [{"stat": "dex", "bonus": 2}, {"stat": "con", "bonus": 1}],
  "age": {},
  "alignment": "",
  "size": "small",
  "speed_ft": 30,
  "speed_notes_ru": "",
  "languages": ["common", "goblin"],
  "traits": [
   {
    "key": "darkvision_60",
    "name_ru": "Тёмное зрение",
    "summary_ru": "Тёмное зрение 60 футов.",
    "mechanics": {"type": "darkvision", "range_ft": 60},
   },
   {
    "key": "fury_of_the_small",
    "name_ru": "Разъярённая мелкота",
    "summary_ru": "Когда наносите урон существу больше вас — можете добавить урон = ваш уровень (1/короткий или длительный отдых).",
    "mechanics": {
     "type": "bonus_damage",
     "amount": "level",
     "uses": "per_short_or_long_rest",
     "uses_max": 1,
     "condition": "target_size_larger_than_you",
     "trigger": "deal_damage_with_attack_or_spell",
    },
   },
   {
    "key": "nimble_escape",
    "name_ru": "Шустрый побег",
    "summary_ru": "Бонусным действием можете Отход или Засада каждый ваш ход.",
    "mechanics": {"type": "bonus_action_options", "options": ["disengage", "hide"], "frequency": "each_turn"},
   },
  ],
  "subraces": [],
  "tags": [],
 },
 {'key': 'grung',
  'name_ru': 'Грунг',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'harengon',
  'name_ru': 'Зайцегон',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'hexblood',
  'name_ru': 'Ведьмовская кровь',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {
  "key": "hobgoblin",
  "name": "Hobgoblin",
  "name_ru": "Хобгоблин",
  "source": "VGM",
  "description_ru": "Дисциплинированный гоблиноид-воин: строевая выучка, холодный расчёт и страх потерять лицо.",
  "asi": [{"stat": "con", "bonus": 2}, {"stat": "int", "bonus": 1}],
  "age": {},
  "alignment": "",
  "size": "medium",
  "speed_ft": 30,
  "speed_notes_ru": "",
  "languages": ["common", "goblin"],
  "traits": [
   {
    "key": "darkvision_60",
    "name_ru": "Тёмное зрение",
    "summary_ru": "Тёмное зрение 60 футов.",
    "mechanics": {"type": "darkvision", "range_ft": 60},
   },
   {
    "key": "martial_training",
    "name_ru": "Боевая подготовка",
    "summary_ru": "Владение лёгкими доспехами и двумя воинскими оружиями на выбор.",
    "mechanics": {
     "type": "proficiency_bundle",
     "armor": ["light"],
     "choose_martial_weapons": 2,
    },
   },
   {
    "key": "saving_face",
    "name_ru": "Сохранить лицо",
    "summary_ru": "Если промахнулись/провалили проверку/спасбросок — добавьте бонус = союзники в 30 футах (макс +5), 1/к/д отдых.",
    "mechanics": {
     "type": "saving_face",
     "range_ft": 30,
     "bonus_formula": "min(allies_within_30ft, 5)",
     "uses": "per_short_or_long_rest",
     "uses_max": 1,
     "trigger": "after_fail_attack_check_or_save",
    },
   },
  ],
  "subraces": [],
  "tags": [],
 },
 {'key': 'kalashtar',
  'name_ru': 'Калаштар',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'kender',
  'name_ru': 'Кендер',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {
  "key": "kenku",
  "name": "Kenku",
  "name_ru": "Кенку",
  "source": "VGM",
  "description_ru": "Проклятые птицеподобные подражатели: они не летают и часто общаются, воспроизводя услышанные звуки и голоса.",
  "asi": [{"stat": "dex", "bonus": 2}, {"stat": "wis", "bonus": 1}],
  "age": {},
  "alignment": "",
  "size": "medium",
  "speed_ft": 30,
  "speed_notes_ru": "",
  "languages": ["common", "auran"],
  "traits": [
   {
    "key": "expert_forgery",
    "name_ru": "Искусный подлог",
    "summary_ru": "Можете копировать почерк и рисунки; для проверки подлога используйте преимущество, если видели оригинал.",
    "mechanics": {"type": "expert_forgery"},
   },
   {
    "key": "kenku_training",
    "name_ru": "Обучение кенку",
    "summary_ru": "Владение двумя навыками на выбор: Акробатика, Обман, Скрытность, Ловкость рук.",
    "mechanics": {
     "type": "choose_skill_proficiencies",
     "choose": 2,
     "from": ["acrobatics", "deception", "stealth", "sleight_of_hand"],
    },
   },
   {
    "key": "mimicry",
    "name_ru": "Подражание",
    "summary_ru": "Можете имитировать звуки и голоса; проверка Мудрости (Проницательность) раскрывает обман.",
    "mechanics": {"type": "mimicry", "counter_check": {"ability": "wis", "skill": "insight"}},
   },
  ],
  "subraces": [],
  "tags": [],
 },
 {
  "key": "kobold",
  "name": "Kobold",
  "name_ru": "Кобольд",
  "source": "VGM",
  "description_ru": "Мелкие дракониды-выживальщики: действуют стаей, любят ловушки и чувствуют себя уверенно рядом с союзниками.",
  "asi": [{"stat": "dex", "bonus": 2}, {"stat": "str", "bonus": -2}],
  "age": {},
  "alignment": "",
  "size": "small",
  "speed_ft": 30,
  "speed_notes_ru": "",
  "languages": ["common", "draconic"],
  "traits": [
   {
    "key": "darkvision_60",
    "name_ru": "Тёмное зрение",
    "summary_ru": "Тёмное зрение 60 футов.",
    "mechanics": {"type": "darkvision", "range_ft": 60},
   },
   {
    "key": "grovel_cower_beg",
    "name_ru": "Пресмыкайся, трусь и умоляй",
    "summary_ru": "Действием отвлекаете врагов рядом; союзники получают преимущество по атакам по ним до начала вашего следующего хода (1/короткий или длительный отдых).",
    "mechanics": {
     "type": "action_debuff",
     "name": "grovel_cower_beg",
     "range_ft": 10,
     "effect": "allies_advantage_on_attacks",
     "duration": "until_start_of_next_turn",
     "uses": "per_short_or_long_rest",
     "uses_max": 1,
    },
   },
   {
    "key": "pack_tactics",
    "name_ru": "Тактика стаи",
    "summary_ru": "Имеете преимущество на атаки, если рядом с целью (в 5 футах) есть ваш союзник, не недееспособный.",
    "mechanics": {"type": "pack_tactics"},
   },
   {
    "key": "sunlight_sensitivity",
    "name_ru": "Чувствительность к солнечному свету",
    "summary_ru": "В ярком солнце помеха к атакам и Восприятию (зрение).",
    "mechanics": {"type": "sunlight_sensitivity"},
   },
  ],
  "subraces": [],
  "tags": [],
 },
 {'key': 'leonin',
  'name_ru': 'Леонин',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'lizardfolk',
  'name_ru': 'Людоящер',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'locathah',
  'name_ru': 'Локата',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'loxodon',
  'name_ru': 'Локсодон',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'minotaur',
  'name_ru': 'Минотавр',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {
  "key": "orc",
  "name": "Orc",
  "name_ru": "Орк",
  "source": "VGM",
  "description_ru": "Суровый воинственный народ: прямолинейны, выносливы и опасны в рывке к добыче.",
  "asi": [{"stat": "str", "bonus": 2}, {"stat": "con", "bonus": 1}, {"stat": "int", "bonus": -2}],
  "age": {},
  "alignment": "",
  "size": "medium",
  "speed_ft": 30,
  "speed_notes_ru": "",
  "languages": ["common", "orc"],
  "traits": [
   {
    "key": "darkvision_60",
    "name_ru": "Тёмное зрение",
    "summary_ru": "Тёмное зрение 60 футов.",
    "mechanics": {"type": "darkvision", "range_ft": 60},
   },
   {
    "key": "aggressive",
    "name_ru": "Агрессивный",
    "summary_ru": "Бонусным действием можете переместиться к видимому врагу (рывок к нему).",
    "mechanics": {"type": "bonus_action_move_toward_enemy"},
   },
   {
    "key": "menacing",
    "name_ru": "Угрожающий",
    "summary_ru": "Владение навыком Запугивание.",
    "mechanics": {"type": "skill_proficiency", "skill": "intimidation"},
   },
   {
    "key": "powerful_build",
    "name_ru": "Мощное телосложение",
    "summary_ru": "Считается на 1 размер больше для переноски/толкания/тяги/подъёма.",
    "mechanics": {
     "type": "powerful_build",
     "applies_to": ["carrying_capacity", "push", "drag", "lift"],
     "effective_size_delta": 1,
    },
   },
  ],
  "subraces": [],
  "tags": [],
 },
 {'key': 'owlin',
  'name_ru': 'Совлин',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'reborn',
  'name_ru': 'Возрождённый',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'satyr',
  'name_ru': 'Сатир',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'shifter',
  'name_ru': 'Шифтер',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'simic_hybrid',
  'name_ru': 'Гибрид Симиков',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {
  "key": "tabaxi",
  "name": "Tabaxi",
  "name_ru": "Табакси",
  "source": "VGM",
  "description_ru": "Кошкоподобные странники: любопытны до одержимости, быстры, ловки и отлично карабкаются.",
  "asi": [{"stat": "dex", "bonus": 2}, {"stat": "cha", "bonus": 1}],
  "age": {},
  "alignment": "",
  "size": "medium",
  "speed_ft": 30,
  "speed_notes_ru": "",
  "languages": ["common", "tabaxi"],
  "traits": [
   {
    "key": "darkvision_60",
    "name_ru": "Тёмное зрение",
    "summary_ru": "Тёмное зрение 60 футов.",
    "mechanics": {"type": "darkvision", "range_ft": 60},
   },
   {
    "key": "feline_agility",
    "name_ru": "Кошачья ловкость",
    "summary_ru": "В свой ход можете удвоить скорость; затем не можете снова, пока не простоите ход без движения.",
    "mechanics": {"type": "feline_agility"},
   },
   {
    "key": "cat_claws",
    "name_ru": "Когти кошки",
    "summary_ru": "Скорость лазания 20 футов; когти — безоружная атака 1d4 рубящего урона.",
    "mechanics": {
     "type": "climb_and_natural_weapon",
     "climb_speed_ft": 20,
     "weapon": {"damage_dice": "1d4", "damage_type": "slashing"},
    },
   },
   {
    "key": "cat_talent_perception_stealth",
    "name_ru": "Кошачий талант",
    "summary_ru": "Владение навыками Восприятие и Скрытность.",
    "mechanics": {"type": "skill_proficiencies", "skills": ["perception", "stealth"]},
   },
  ],
  "subraces": [],
  "tags": [],
 },
 {
  "key": "tortle",
  "name": "Tortle",
  "name_ru": "Тортл",
  "source": "TP",
  "description_ru": "Черепахолюди: спокойные кочевники, защищённые панцирем и приспособленные к воде и берегам.",
  "asi": [{"stat": "str", "bonus": 2}, {"stat": "wis", "bonus": 1}],
  "age": {},
  "alignment": "",
  "size": "medium",
  "speed_ft": 30,
  "speed_notes_ru": "",
  "languages": ["common", "aquan"],
  "traits": [
   {
    "key": "natural_armor_shell",
    "name_ru": "Природная броня",
    "summary_ru": "Ваш КД = 17 (панцирь). Не складывается с ношением доспехов.",
    "mechanics": {"type": "natural_armor", "ac": 17, "no_armor_stack": True},
   },
   {
    "key": "claws",
    "name_ru": "Когти",
    "summary_ru": "Когти — безоружная атака 1d4 рубящего урона.",
    "mechanics": {"type": "natural_weapon", "name_ru": "Когти", "damage_dice": "1d4", "damage_type": "slashing", "kind": "unarmed"},
   },
   {
    "key": "hold_breath",
    "name_ru": "Задержка дыхания",
    "summary_ru": "Можете задерживать дыхание до 1 часа.",
    "mechanics": {"type": "hold_breath", "duration": "1_hour"},
   },
   {
    "key": "shell_defense",
    "name_ru": "Защита панцирем",
    "summary_ru": "Действием прячете конечности: КД +4, преимущество к Сил/Тел спасброскам; помеха к Лов спасброскам; скорость 0.",
    "mechanics": {"type": "shell_defense"},
   },
   {
    "key": "survival_proficiency",
    "name_ru": "Выживание",
    "summary_ru": "Владение навыком Выживание.",
    "mechanics": {"type": "skill_proficiency", "skill": "survival"},
   },
  ],
  "subraces": [],
  "tags": [],
 },
 {
  "key": "triton",
  "name": "Triton",
  "name_ru": "Тритон",
  "source": "VGM",
  "description_ru": "Амфибийные защитники морских глубин: владеют магией воды и общаются с морскими существами.",
  "asi": [{"stat": "str", "bonus": 1}, {"stat": "con", "bonus": 1}, {"stat": "cha", "bonus": 1}],
  "age": {},
  "alignment": "",
  "size": "medium",
  "speed_ft": 30,
  "speed_notes_ru": "",
  "languages": ["common", "primordial"],
  "traits": [
   {
    "key": "darkvision_60",
    "name_ru": "Тёмное зрение",
    "summary_ru": "Тёмное зрение 60 футов.",
    "mechanics": {"type": "darkvision", "range_ft": 60},
   },
   {
    "key": "amphibious",
    "name_ru": "Амфибия",
    "summary_ru": "Можете дышать и воздухом, и водой.",
    "mechanics": {"type": "amphibious"},
   },
   {
    "key": "control_air_and_water",
    "name_ru": "Управление воздухом и водой",
    "summary_ru": "Знаете заговор «Создание/уничтожение воды». На 3 ур. «Порыв ветра», на 5 ур. «Стена воды» (Харизма).",
    "mechanics": {
     "type": "innate_spellcasting",
     "ability": "cha",
     "spells": [
      {"level": 0, "name": "create_or_destroy_water", "frequency": "at_will"},
      {"level": 2, "name": "gust_of_wind", "frequency": "1_per_long_rest", "min_level": 3},
      {"level": 3, "name": "wall_of_water", "frequency": "1_per_long_rest", "min_level": 5},
     ],
    },
   },
   {
    "key": "guardians_of_the_depths",
    "name_ru": "Стражи глубин",
    "summary_ru": "Сопротивление холоду и давлению глубин; игнорируете недостатки глубоководной среды.",
    "mechanics": {"type": "guardians_of_the_depths"},
   },
   {
    "key": "emissary_of_the_sea",
    "name_ru": "Посланник моря",
    "summary_ru": "Можете общаться простыми идеями с морскими зверями.",
    "mechanics": {"type": "speak_with_beasts", "scope": "sea_beasts"},
   },
  ],
  "subraces": [],
  "tags": [],
 },
 {'key': 'warforged',
  'name_ru': 'Кованый',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'yuan_ti_pureblood',
  'name_ru': 'Юань-ти',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'}]

COMBINED_RACE_CATALOG: list[dict[str, Any]] = BASE_RACE_CATALOG + EXTERNAL_RACE_CATALOG


CLASS_CATALOG, RACE_CATALOG = load_catalogs(
    base_classes=BASE_CLASS_CATALOG,
    base_races=COMBINED_RACE_CATALOG,
)


CLASS_ALIASES: dict[str, str] = {
    "mage": "wizard",
}


RACE_ALIASES: dict[str, str] = {
    "man": "human",
    "human_variant": "human",
}


CLASS_BY_KEY: dict[str, dict[str, Any]] = {item["key"]: item for item in CLASS_CATALOG}
RACE_BY_KEY: dict[str, dict[str, Any]] = {item["key"]: item for item in RACE_CATALOG}


def resolve_class_key(raw_key: Any) -> str:
    key = _slug(raw_key)
    if not key:
        return ""
    return CLASS_ALIASES.get(key, key)


def resolve_race_key(raw_key: Any) -> str:
    key = _slug(raw_key)
    if not key:
        return ""
    return RACE_ALIASES.get(key, key)


def resolve_class(raw_key: Any) -> dict[str, Any] | None:
    return CLASS_BY_KEY.get(resolve_class_key(raw_key))


def resolve_race(raw_key: Any) -> dict[str, Any] | None:
    return RACE_BY_KEY.get(resolve_race_key(raw_key))


def class_hit_die_by_catalog(class_kit: Any, class_skin: Any) -> int:
    by_kit = resolve_class(class_kit)
    if by_kit is not None:
        return max(1, int(by_kit.get("hit_die") or 8))

    by_skin = resolve_class(class_skin)
    if by_skin is not None:
        return max(1, int(by_skin.get("hit_die") or 8))

    return 8


def race_speed_ft_by_catalog(race_kit: Any, race_skin: Any) -> int:
    by_kit = resolve_race(race_kit)
    if by_kit is not None:
        return max(0, int(by_kit.get("speed_ft") or 30))

    by_skin = resolve_race(race_skin)
    if by_skin is not None:
        return max(0, int(by_skin.get("speed_ft") or 30))

    return 30
