from __future__ import annotations

from typing import Any


PHB_CLASS_KEYS: tuple[str, ...] = (
    "barbarian",
    "bard",
    "cleric",
    "druid",
    "fighter",
    "monk",
    "paladin",
    "ranger",
    "rogue",
    "sorcerer",
    "warlock",
    "wizard",
)


BASE_CLASS_CATALOG: list[dict[str, Any]] = [
    {
        "key": "barbarian",
        "name": "Barbarian",
        "name_ru": "Варвар",
        "source": "PHB",
        "description_ru": "Неистовый воин, полагающийся на ярость, стойкость и грубую силу.",
        "hit_die": 12,
        "primary_abilities": ["str"],
        "saving_throws": ["str", "con"],
        "proficiencies": {
            "armor": ["light", "medium", "shields"],
            "weapons": ["simple", "martial"],
            "tools": [],
            "skills_choose": {
                "count": 2,
                "from": ["athletics", "intimidation", "nature", "perception", "survival", "animal_handling"],
            },
        },
        "skill_choices": {},
        "starting_equipment": [
            {
                "key": "phb_barbarian_starting_equipment",
                "name_ru": "Стартовое снаряжение варвара",
                "summary_ru": "а) двуручный топор или б) любое воинское рукопашное оружие; а) два ручных топора или б) любое простое оружие; набор путешественника и 4 метательных копья.",
            }
        ],
        "features_by_level": {
            1: [
                {"key": "rage", "name_ru": "Ярость", "summary_ru": "В бою усиливает урон и выживаемость.", "mechanics": {}},
                {"key": "unarmored_defense", "name_ru": "Защита без доспехов", "summary_ru": "КД рассчитывается от Телосложения и Ловкости.", "mechanics": {}},
            ],
            2: [
                {"key": "reckless_attack", "name_ru": "Безрассудная атака", "summary_ru": "Можно атаковать агрессивно, повышая шанс попадания ценой защиты.", "mechanics": {}},
                {"key": "danger_sense", "name_ru": "Чувство опасности", "summary_ru": "Лучше избегает видимых угроз и ловушек.", "mechanics": {}},
            ],
            3: [
                {"key": "primal_path", "name_ru": "Путь дикости", "summary_ru": "Выбор подкласса варвара.", "mechanics": {"type": "subclass_choice"}},
            ],
            4: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            5: [
                {"key": "extra_attack", "name_ru": "Дополнительная атака", "summary_ru": "Совершает больше атак действием.", "mechanics": {}},
                {"key": "fast_movement", "name_ru": "Быстрое передвижение", "summary_ru": "Увеличивает скорость передвижения.", "mechanics": {}},
            ],
            6: [{"key": "path_feature_6", "name_ru": "Особенность пути (6)", "summary_ru": "Классовая особенность выбранного пути на 6 уровне.", "mechanics": {}}],
            7: [{"key": "feral_instinct", "name_ru": "Звериный инстинкт", "summary_ru": "Быстрее реагирует на начало схватки.", "mechanics": {}}],
            8: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            9: [{"key": "brutal_critical_1", "name_ru": "Жестокий критический удар (1)", "summary_ru": "Критические удары наносят больше урона.", "mechanics": {}}],
            10: [{"key": "path_feature_10", "name_ru": "Особенность пути (10)", "summary_ru": "Классовая особенность выбранного пути на 10 уровне.", "mechanics": {}}],
            11: [{"key": "relentless_rage", "name_ru": "Неукротимая ярость", "summary_ru": "Может удержаться на ногах после тяжёлого удара.", "mechanics": {}}],
            12: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            13: [{"key": "brutal_critical_2", "name_ru": "Жестокий критический удар (2)", "summary_ru": "Критические удары становятся ещё опаснее.", "mechanics": {}}],
            14: [{"key": "path_feature_14", "name_ru": "Особенность пути (14)", "summary_ru": "Классовая особенность выбранного пути на 14 уровне.", "mechanics": {}}],
            15: [{"key": "persistent_rage", "name_ru": "Постоянная ярость", "summary_ru": "Ярость удерживается дольше в сражении.", "mechanics": {}}],
            16: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            17: [{"key": "brutal_critical_3", "name_ru": "Жестокий критический удар (3)", "summary_ru": "Максимальная ступень усиления критических ударов.", "mechanics": {}}],
            18: [{"key": "indomitable_might", "name_ru": "Несокрушимая мощь", "summary_ru": "Чистая сила помогает в проверках даже при плохом броске.", "mechanics": {}}],
            19: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            20: [{"key": "primal_champion", "name_ru": "Первобытный чемпион", "summary_ru": "Пик физической мощи и выносливости варвара.", "mechanics": {}}],
        },
        "subclasses": [
            {"key": "berserker", "name_ru": "Путь берсерка", "features_by_level": {}},
            {"key": "totem_warrior", "name_ru": "Путь тотемного воина", "features_by_level": {}},
        ],
        "spellcasting": {},
        "spell_lists": {},
        "tags": [],
    },
    {
        "key": "bard",
        "name": "Bard",
        "name_ru": "Бард",
        "source": "PHB",
        "description_ru": "Вдохновляющий заклинатель, использующий музыку, слово и харизму для поддержки союзников и управления ходом сцены.",
        "hit_die": 8,
        "primary_abilities": ["cha"],
        "saving_throws": ["dex", "cha"],
        "proficiencies": {
            "armor": ["light"],
            "weapons": ["simple", "longsword", "shortsword", "rapier", "hand_crossbow"],
            "tools": ["musical_instrument", "musical_instrument", "musical_instrument"],
            "skills_choose": {
                "count": 3,
                "from": [
                    "athletics",
                    "acrobatics",
                    "sleight_of_hand",
                    "stealth",
                    "arcana",
                    "history",
                    "investigation",
                    "nature",
                    "religion",
                    "animal_handling",
                    "insight",
                    "medicine",
                    "perception",
                    "survival",
                    "deception",
                    "intimidation",
                    "performance",
                    "persuasion",
                ],
            },
        },
        "skill_choices": {},
        "starting_equipment": [
            {
                "key": "phb_bard_starting_equipment",
                "name_ru": "Стартовое снаряжение барда",
                "summary_ru": "а) рапира, б) длинный меч или в) любое простое оружие; а) набор дипломата или б) набор артиста; а) лютня или б) любой другой музыкальный инструмент; кожаный доспех и кинжал.",
            }
        ],
        "features_by_level": {
            1: [
                {
                    "key": "spellcasting",
                    "name_ru": "Использование заклинаний",
                    "summary_ru": "Бард использует Харизму для заклинаний и может творить известные заклинания из списка барда.",
                    "mechanics": {
                        "type": "spellcasting",
                        "ability": "cha",
                        "progression": "full",
                        "known_style": "known",
                        "focus": ["musical_instrument"],
                        "ritual": True,
                    },
                },
                {"key": "bardic_inspiration", "name_ru": "Вдохновение барда", "summary_ru": "Бонусным действием вдохновляет союзника костью вдохновения.", "mechanics": {"type": "bardic_inspiration"}},
            ],
            2: [
                {"key": "jack_of_all_trades", "name_ru": "Мастер на все руки", "summary_ru": "Добавляет половину бонуса мастерства к проверкам, где мастерство не применяется.", "mechanics": {}},
                {"key": "song_of_rest", "name_ru": "Песнь отдыха", "summary_ru": "Во время короткого отдыха союзники дополнительно восстанавливают хиты.", "mechanics": {}},
            ],
            3: [
                {"key": "bard_college", "name_ru": "Коллегия бардов", "summary_ru": "Выбор подкласса барда.", "mechanics": {"type": "subclass_choice"}},
                {"key": "expertise", "name_ru": "Компетентность", "summary_ru": "Удвоение бонуса мастерства для выбранных навыков.", "mechanics": {}},
            ],
            4: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            5: [{"key": "font_of_inspiration", "name_ru": "Источник вдохновения", "summary_ru": "Вдохновение барда восстанавливается после короткого отдыха.", "mechanics": {}}],
            6: [{"key": "countercharm", "name_ru": "Контрочарование", "summary_ru": "Использует выступление, чтобы дать преимущество против очарования и испуга.", "mechanics": {}}],
            8: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            10: [
                {"key": "expertise_2", "name_ru": "Компетентность", "summary_ru": "Выбор ещё двух навыков для удвоенного бонуса мастерства.", "mechanics": {}},
                {"key": "magical_secrets", "name_ru": "Тайны магии", "summary_ru": "Изучает заклинания из списков других классов.", "mechanics": {}},
            ],
            12: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            14: [{"key": "magical_secrets_2", "name_ru": "Тайны магии", "summary_ru": "Изучает дополнительные заклинания из списков других классов.", "mechanics": {}}],
            16: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            18: [{"key": "magical_secrets_3", "name_ru": "Тайны магии", "summary_ru": "Изучает дополнительные заклинания из списков других классов.", "mechanics": {}}],
            19: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            20: [{"key": "superior_inspiration", "name_ru": "Превосходное вдохновение", "summary_ru": "Если вдохновение закончилось, бард получает одно использование в начале столкновения.", "mechanics": {}}],
        },
        "subclasses": [
            {"key": "lore", "name_ru": "Коллегия знаний", "features_by_level": {}},
            {"key": "valor", "name_ru": "Коллегия доблести", "features_by_level": {}},
        ],
        "spellcasting": {
            "type": "full_caster_known",
            "ability": "cha",
            "focus": ["musical_instrument"],
            "ritual": True,
            "spell_list_key": "bard",
        },
        "spell_lists": {"class": "bard"},
        "tags": [],
    },
    {
        "key": "cleric",
        "name": "Cleric",
        "name_ru": "Жрец",
        "source": "PHB",
        "description_ru": "Священнослужитель, проводник божественной силы, сочетающий поддержку, защиту и силу домена своего божества.",
        "hit_die": 8,
        "primary_abilities": ["wis"],
        "saving_throws": ["wis", "cha"],
        "proficiencies": {
            "armor": ["light", "medium", "shields"],
            "weapons": ["simple"],
            "tools": [],
            "skills_choose": {
                "count": 2,
                "from": ["history", "insight", "medicine", "persuasion", "religion"],
            },
        },
        "skill_choices": {},
        "starting_equipment": [
            {
                "key": "phb_cleric_starting_equipment",
                "name_ru": "Стартовое снаряжение жреца",
                "summary_ru": "а) булава или б) боевой молот (если есть владение); а) чешуйчатый доспех, б) кожаный доспех или в) кольчуга (если есть владение); а) лёгкий арбалет и 20 болтов или б) любое простое оружие; а) набор священника или б) набор путешественника; щит и священный символ.",
            }
        ],
        "features_by_level": {
            1: [
                {
                    "key": "spellcasting",
                    "name_ru": "Использование заклинаний",
                    "summary_ru": "Жрец подготавливает заклинания из списка жреца и использует Мудрость как базовую характеристику заклинаний.",
                    "mechanics": {
                        "type": "spellcasting",
                        "ability": "wis",
                        "progression": "full",
                        "known_style": "prepared",
                        "focus": ["holy_symbol"],
                        "ritual": True,
                    },
                },
                {"key": "divine_domain", "name_ru": "Божественный домен", "summary_ru": "Выбор домена, определяющего силу жреца.", "mechanics": {"type": "subclass_choice"}},
            ],
            2: [
                {"key": "channel_divinity", "name_ru": "Божественный канал", "summary_ru": "Направляет божественную силу для эффектов домена и изгнания нежити.", "mechanics": {}},
                {"key": "domain_feature_2", "name_ru": "Умение домена (2)", "summary_ru": "Особенность выбранного божественного домена.", "mechanics": {}},
            ],
            4: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            5: [{"key": "destroy_undead", "name_ru": "Уничтожение нежити", "summary_ru": "Изгнанная нежить низкой опасности может быть уничтожена.", "mechanics": {}}],
            6: [
                {"key": "channel_divinity_2", "name_ru": "Божественный канал (2)", "summary_ru": "Жрец использует Божественный канал дважды между отдыхами.", "mechanics": {}},
                {"key": "domain_feature_6", "name_ru": "Умение домена (6)", "summary_ru": "Новая особенность выбранного домена.", "mechanics": {}},
            ],
            8: [
                {"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}},
                {"key": "domain_feature_8", "name_ru": "Умение домена (8)", "summary_ru": "Усиление выбранного домена на 8 уровне.", "mechanics": {}},
            ],
            10: [{"key": "divine_intervention", "name_ru": "Божественное вмешательство", "summary_ru": "Может воззвать к своему божеству о прямой помощи.", "mechanics": {}}],
            12: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            16: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            17: [{"key": "domain_feature_17", "name_ru": "Умение домена (17)", "summary_ru": "Высшая особенность выбранного домена.", "mechanics": {}}],
            18: [{"key": "channel_divinity_3", "name_ru": "Божественный канал (3)", "summary_ru": "Жрец использует Божественный канал трижды между отдыхами.", "mechanics": {}}],
            19: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            20: [{"key": "improved_divine_intervention", "name_ru": "Совершенное божественное вмешательство", "summary_ru": "Божественное вмешательство становится гарантированным.", "mechanics": {}}],
        },
        "subclasses": [
            {"key": "knowledge", "name_ru": "Домен знаний", "features_by_level": {}},
            {"key": "life", "name_ru": "Домен жизни", "features_by_level": {}},
            {"key": "light", "name_ru": "Домен света", "features_by_level": {}},
            {"key": "nature", "name_ru": "Домен природы", "features_by_level": {}},
            {"key": "tempest", "name_ru": "Домен бури", "features_by_level": {}},
            {"key": "trickery", "name_ru": "Домен обмана", "features_by_level": {}},
            {"key": "war", "name_ru": "Домен войны", "features_by_level": {}},
        ],
        "spellcasting": {
            "type": "full_caster_prepared",
            "ability": "wis",
            "focus": ["holy_symbol"],
            "ritual": True,
            "spell_list_key": "cleric",
        },
        "spell_lists": {"class": "cleric"},
        "tags": [],
    },
    {
        "key": "druid",
        "name": "Druid",
        "name_ru": "Друид",
        "source": "PHB",
        "description_ru": "Хранитель природной магии, превращающийся в зверей и управляющий силами мира.",
        "hit_die": 8,
        "primary_abilities": ["wis"],
        "saving_throws": ["int", "wis"],
        "proficiencies": {
            "armor": ["light", "medium", "shields"],
            "weapons": ["club", "dagger", "dart", "javelin", "mace", "quarterstaff", "scimitar", "sickle", "sling", "spear"],
            "tools": ["herbalism_kit"],
            "skills_choose": {
                "count": 2,
                "from": ["arcana", "animal_handling", "insight", "medicine", "nature", "perception", "religion", "survival"],
            },
        },
        "skill_choices": {},
        "starting_equipment": [
            {
                "key": "phb_druid_starting_equipment",
                "name_ru": "Стартовое снаряжение друида",
                "summary_ru": "а) деревянный щит или б) любое простое оружие; а) серп или б) любое простое рукопашное оружие; кожаный доспех, набор исследователя и друидический фокус.",
            }
        ],
        "features_by_level": {
            1: [
                {
                    "key": "druidic",
                    "name_ru": "Друидический",
                    "summary_ru": "Знает тайный язык друидов.",
                    "mechanics": {},
                },
                {
                    "key": "spellcasting",
                    "name_ru": "Использование заклинаний",
                    "summary_ru": "Друид подготавливает заклинания из списка друида и использует Мудрость как базовую характеристику.",
                    "mechanics": {
                        "type": "spellcasting",
                        "ability": "wis",
                        "progression": "full",
                        "known_style": "prepared",
                        "focus": ["druidic_focus"],
                        "ritual": True,
                    },
                },
            ],
            2: [
                {"key": "wild_shape", "name_ru": "Дикий облик", "summary_ru": "Может принимать форму зверя.", "mechanics": {}},
                {"key": "druid_circle", "name_ru": "Круг друидов", "summary_ru": "Выбор подкласса друида.", "mechanics": {"type": "subclass_choice"}},
            ],
            4: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            6: [{"key": "circle_feature_6", "name_ru": "Умение круга (6)", "summary_ru": "Особенность выбранного круга на 6 уровне.", "mechanics": {}}],
            8: [
                {"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}},
                {"key": "wild_shape_improvement", "name_ru": "Улучшение дикого облика", "summary_ru": "Дикий облик получает новые формы и мобильность.", "mechanics": {}},
            ],
            10: [{"key": "circle_feature_10", "name_ru": "Умение круга (10)", "summary_ru": "Особенность выбранного круга на 10 уровне.", "mechanics": {}}],
            12: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            14: [{"key": "circle_feature_14", "name_ru": "Умение круга (14)", "summary_ru": "Высшая особенность выбранного круга.", "mechanics": {}}],
            16: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            18: [
                {"key": "timeless_body", "name_ru": "Безвременное тело", "summary_ru": "Стареет медленнее и хуже ощущает возраст.", "mechanics": {}},
                {"key": "beast_spells", "name_ru": "Заклинания зверя", "summary_ru": "Может накладывать заклинания в форме зверя.", "mechanics": {}},
            ],
            19: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            20: [{"key": "archdruid", "name_ru": "Архидруид", "summary_ru": "Почти без ограничений использует Дикий облик.", "mechanics": {}}],
        },
        "subclasses": [
            {"key": "land", "name_ru": "Круг Земли", "features_by_level": {}},
            {"key": "moon", "name_ru": "Круг Луны", "features_by_level": {}},
        ],
        "spellcasting": {
            "type": "full_caster_prepared",
            "ability": "wis",
            "focus": ["druidic_focus"],
            "ritual": True,
            "spell_list_key": "druid",
        },
        "spell_lists": {"class": "druid"},
        "tags": [],
    },
    {
        "key": "fighter",
        "name": "Fighter",
        "name_ru": "Воин",
        "source": "PHB",
        "description_ru": "Универсальный мастер оружия и доспехов, доводящий боевое ремесло до совершенства.",
        "hit_die": 10,
        "primary_abilities": ["str", "dex"],
        "saving_throws": ["str", "con"],
        "proficiencies": {
            "armor": ["light", "medium", "heavy", "shields"],
            "weapons": ["simple", "martial"],
            "tools": [],
            "skills_choose": {
                "count": 2,
                "from": ["acrobatics", "animal_handling", "athletics", "history", "insight", "intimidation", "perception", "survival"],
            },
        },
        "skill_choices": {},
        "starting_equipment": [
            {
                "key": "phb_fighter_starting_equipment",
                "name_ru": "Стартовое снаряжение воина",
                "summary_ru": "а) кольчуга или б) кожаный доспех, длинный лук и 20 стрел; а) воинское оружие и щит или б) два воинских оружия; а) лёгкий арбалет и 20 болтов или б) два ручных топора; а) набор исследователя подземелий или б) набор путешественника.",
            }
        ],
        "features_by_level": {
            1: [
                {"key": "fighting_style", "name_ru": "Стиль боя", "summary_ru": "Выбор боевого стиля, определяющего сильную сторону воина.", "mechanics": {}},
                {"key": "second_wind", "name_ru": "Второе дыхание", "summary_ru": "Может быстро восстановить часть хитов в бою.", "mechanics": {}},
            ],
            2: [{"key": "action_surge", "name_ru": "Всплеск действий", "summary_ru": "Иногда получает дополнительное действие в ход.", "mechanics": {}}],
            3: [{"key": "martial_archetype", "name_ru": "Воинский архетип", "summary_ru": "Выбор подкласса воина.", "mechanics": {"type": "subclass_choice"}}],
            4: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            5: [{"key": "extra_attack", "name_ru": "Дополнительная атака", "summary_ru": "Совершает больше атак действием.", "mechanics": {}}],
            6: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            7: [{"key": "archetype_feature_7", "name_ru": "Умение архетипа (7)", "summary_ru": "Особенность выбранного архетипа на 7 уровне.", "mechanics": {}}],
            8: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            9: [{"key": "indomitable_1", "name_ru": "Несгибаемый (1)", "summary_ru": "Может перебросить неудачный спасбросок.", "mechanics": {}}],
            10: [{"key": "archetype_feature_10", "name_ru": "Умение архетипа (10)", "summary_ru": "Особенность выбранного архетипа на 10 уровне.", "mechanics": {}}],
            11: [{"key": "extra_attack_2", "name_ru": "Дополнительная атака (2)", "summary_ru": "Совершает три атаки действием.", "mechanics": {}}],
            12: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            13: [{"key": "indomitable_2", "name_ru": "Несгибаемый (2)", "summary_ru": "Ещё одно применение Несгибаемого между отдыхами.", "mechanics": {}}],
            14: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            15: [{"key": "archetype_feature_15", "name_ru": "Умение архетипа (15)", "summary_ru": "Особенность выбранного архетипа на 15 уровне.", "mechanics": {}}],
            16: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            17: [
                {"key": "action_surge_2", "name_ru": "Всплеск действий (2)", "summary_ru": "Получает два использования Всплеска действий между отдыхами.", "mechanics": {}},
                {"key": "indomitable_3", "name_ru": "Несгибаемый (3)", "summary_ru": "Третье использование Несгибаемого между отдыхами.", "mechanics": {}},
            ],
            18: [{"key": "archetype_feature_18", "name_ru": "Умение архетипа (18)", "summary_ru": "Высшая особенность выбранного архетипа.", "mechanics": {}}],
            19: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            20: [{"key": "extra_attack_3", "name_ru": "Дополнительная атака (3)", "summary_ru": "Совершает четыре атаки действием.", "mechanics": {}}],
        },
        "subclasses": [
            {"key": "champion", "name_ru": "Чемпион", "features_by_level": {}},
            {"key": "battle_master", "name_ru": "Мастер боевых искусств", "features_by_level": {}},
            {"key": "eldritch_knight", "name_ru": "Мистический рыцарь", "features_by_level": {}},
        ],
        "spellcasting": {},
        "spell_lists": {},
        "tags": [],
    },
    {
        "key": "monk",
        "name": "Monk",
        "name_ru": "Монах",
        "source": "PHB",
        "description_ru": "Дисциплинированный мастер тела и духа, использующий ки и безоружные техники.",
        "hit_die": 8,
        "primary_abilities": ["dex", "wis"],
        "saving_throws": ["str", "dex"],
        "proficiencies": {
            "armor": [],
            "weapons": ["simple", "shortsword"],
            "tools": [],
            "tools_choose": {"count": 1, "from": ["artisan_tools", "musical_instrument"]},
            "skills_choose": {
                "count": 2,
                "from": ["acrobatics", "athletics", "history", "insight", "religion", "stealth"],
            },
        },
        "skill_choices": {},
        "starting_equipment": [
            {
                "key": "phb_monk_starting_equipment",
                "name_ru": "Стартовое снаряжение монаха",
                "summary_ru": "а) короткий меч или б) любое простое оружие; а) набор исследователя подземелий или б) набор путешественника; 10 дротиков.",
            }
        ],
        "features_by_level": {
            1: [
                {"key": "unarmored_defense", "name_ru": "Защита без доспехов", "summary_ru": "КД рассчитывается от Мудрости и Ловкости.", "mechanics": {}},
                {"key": "martial_arts", "name_ru": "Боевые искусства", "summary_ru": "Безоружные удары и монашеское оружие становятся смертоноснее.", "mechanics": {}},
            ],
            2: [
                {"key": "ki", "name_ru": "Ки", "summary_ru": "Тратит очки ки на специальные боевые техники.", "mechanics": {}},
                {"key": "unarmored_movement", "name_ru": "Передвижение без доспехов", "summary_ru": "Двигается быстрее без доспехов и щита.", "mechanics": {}},
            ],
            3: [
                {"key": "monastic_tradition", "name_ru": "Монашеская традиция", "summary_ru": "Выбор подкласса монаха.", "mechanics": {"type": "subclass_choice"}},
                {"key": "deflect_missiles", "name_ru": "Отражение снарядов", "summary_ru": "Может уменьшать урон от стрел и подобных атак.", "mechanics": {}},
            ],
            4: [
                {"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}},
                {"key": "slow_fall", "name_ru": "Замедленное падение", "summary_ru": "Снижает урон от падения.", "mechanics": {}},
            ],
            5: [
                {"key": "extra_attack", "name_ru": "Дополнительная атака", "summary_ru": "Совершает больше атак действием.", "mechanics": {}},
                {"key": "stunning_strike", "name_ru": "Ошеломляющий удар", "summary_ru": "Может оглушить противника ударом ки.", "mechanics": {}},
            ],
            6: [
                {"key": "ki_empowered_strikes", "name_ru": "Удары, усиленные ки", "summary_ru": "Безоружные удары считаются магическими.", "mechanics": {}},
                {"key": "monastic_feature_6", "name_ru": "Умение традиции (6)", "summary_ru": "Особенность выбранной монашеской традиции.", "mechanics": {}},
            ],
            7: [
                {"key": "evasion", "name_ru": "Уклонение", "summary_ru": "Лучше избегает урона от областных эффектов.", "mechanics": {}},
                {"key": "stillness_of_mind", "name_ru": "Спокойствие разума", "summary_ru": "Может сбросить очарование и испуг действием.", "mechanics": {}},
            ],
            8: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            9: [{"key": "unarmored_movement_improvement", "name_ru": "Улучшенное передвижение", "summary_ru": "Может перемещаться по вертикалям и по воде в движении.", "mechanics": {}}],
            10: [{"key": "purity_of_body", "name_ru": "Чистота тела", "summary_ru": "Иммунитет к болезням и яду.", "mechanics": {}}],
            11: [{"key": "monastic_feature_11", "name_ru": "Умение традиции (11)", "summary_ru": "Особенность выбранной монашеской традиции.", "mechanics": {}}],
            12: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            13: [{"key": "tongue_of_sun_and_moon", "name_ru": "Язык солнца и луны", "summary_ru": "Понимает речь любых существ и сам может быть понят.", "mechanics": {}}],
            14: [{"key": "diamond_soul", "name_ru": "Алмазная душа", "summary_ru": "Получает мастерство во всех спасбросках.", "mechanics": {}}],
            15: [{"key": "timeless_body", "name_ru": "Безвременное тело", "summary_ru": "Возраст почти не влияет на тело монаха.", "mechanics": {}}],
            16: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            17: [{"key": "monastic_feature_17", "name_ru": "Умение традиции (17)", "summary_ru": "Высшая особенность выбранной монашеской традиции.", "mechanics": {}}],
            18: [{"key": "empty_body", "name_ru": "Пустое тело", "summary_ru": "Использует ки для невидимости и защиты от урона.", "mechanics": {}}],
            19: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            20: [{"key": "perfect_self", "name_ru": "Совершенное я", "summary_ru": "В начале боя восстанавливает немного ки, если оно закончилось.", "mechanics": {}}],
        },
        "subclasses": [
            {"key": "open_hand", "name_ru": "Путь открытой ладони", "features_by_level": {}},
            {"key": "shadow", "name_ru": "Путь тени", "features_by_level": {}},
            {"key": "four_elements", "name_ru": "Путь четырёх стихий", "features_by_level": {}},
        ],
        "spellcasting": {},
        "spell_lists": {},
        "tags": [],
    },
    {
        "key": "paladin",
        "name": "Paladin",
        "name_ru": "Паладин",
        "source": "PHB",
        "description_ru": "Священный воитель, сочетающий тяжёлый бой, клятвы и божественную магию.",
        "hit_die": 10,
        "primary_abilities": ["str", "cha"],
        "saving_throws": ["wis", "cha"],
        "proficiencies": {
            "armor": ["light", "medium", "heavy", "shields"],
            "weapons": ["simple", "martial"],
            "tools": [],
            "skills_choose": {
                "count": 2,
                "from": ["athletics", "insight", "intimidation", "medicine", "persuasion", "religion"],
            },
        },
        "skill_choices": {},
        "starting_equipment": [
            {
                "key": "phb_paladin_starting_equipment",
                "name_ru": "Стартовое снаряжение паладина",
                "summary_ru": "а) воинское оружие и щит или б) два воинских оружия; а) 5 метательных копий или б) любое простое рукопашное оружие; а) набор священника или б) набор исследователя подземелий; кольчуга и священный символ.",
            }
        ],
        "features_by_level": {
            1: [
                {"key": "divine_sense", "name_ru": "Божественное чутьё", "summary_ru": "Чувствует сильное зло, добро и святые места.", "mechanics": {}},
                {"key": "lay_on_hands", "name_ru": "Наложение рук", "summary_ru": "Лечит раны и очищает болезни запасом божественной силы.", "mechanics": {}},
            ],
            2: [
                {"key": "fighting_style", "name_ru": "Стиль боя", "summary_ru": "Выбор боевого стиля паладина.", "mechanics": {}},
                {
                    "key": "spellcasting",
                    "name_ru": "Использование заклинаний",
                    "summary_ru": "Паладин подготавливает заклинания и использует Харизму как базовую характеристику.",
                    "mechanics": {
                        "type": "spellcasting",
                        "ability": "cha",
                        "progression": "half",
                        "known_style": "prepared",
                        "spell_list_key": "paladin",
                    },
                },
                {"key": "divine_smite", "name_ru": "Божественная кара", "summary_ru": "Тратит ячейки заклинаний, чтобы усиливать удары светом.", "mechanics": {}},
            ],
            3: [
                {"key": "divine_health", "name_ru": "Божественное здоровье", "summary_ru": "Иммунитет к болезням.", "mechanics": {}},
                {"key": "sacred_oath", "name_ru": "Священная клятва", "summary_ru": "Выбор подкласса паладина.", "mechanics": {"type": "subclass_choice"}},
            ],
            4: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            5: [{"key": "extra_attack", "name_ru": "Дополнительная атака", "summary_ru": "Совершает больше атак действием.", "mechanics": {}}],
            6: [{"key": "aura_of_protection", "name_ru": "Аура защиты", "summary_ru": "Союзники рядом получают бонус к спасброскам.", "mechanics": {}}],
            7: [{"key": "oath_feature_7", "name_ru": "Умение клятвы (7)", "summary_ru": "Особенность выбранной клятвы на 7 уровне.", "mechanics": {}}],
            8: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            10: [{"key": "aura_of_courage", "name_ru": "Аура отваги", "summary_ru": "Паладин и союзники рядом не боятся испуга.", "mechanics": {}}],
            11: [{"key": "improved_divine_smite", "name_ru": "Улучшенная божественная кара", "summary_ru": "Каждый удар паладина несёт дополнительный светлый урон.", "mechanics": {}}],
            12: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            14: [{"key": "cleansing_touch", "name_ru": "Очищающее касание", "summary_ru": "Может снять заклинание касанием.", "mechanics": {}}],
            15: [{"key": "oath_feature_15", "name_ru": "Умение клятвы (15)", "summary_ru": "Особенность выбранной клятвы на 15 уровне.", "mechanics": {}}],
            16: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            18: [{"key": "aura_improvements", "name_ru": "Улучшенные ауры", "summary_ru": "Ауры паладина распространяются дальше.", "mechanics": {}}],
            19: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            20: [{"key": "oath_feature_20", "name_ru": "Высшая особенность клятвы", "summary_ru": "Пиковая сила выбранной священной клятвы.", "mechanics": {}}],
        },
        "subclasses": [
            {"key": "devotion", "name_ru": "Клятва верности", "features_by_level": {}},
            {"key": "ancients", "name_ru": "Клятва древних", "features_by_level": {}},
            {"key": "vengeance", "name_ru": "Клятва мести", "features_by_level": {}},
        ],
        "spellcasting": {
            "type": "half_caster_prepared",
            "ability": "cha",
            "spell_list_key": "paladin",
        },
        "spell_lists": {"class": "paladin"},
        "tags": [],
    },
    {
        "key": "ranger",
        "name": "Ranger",
        "name_ru": "Следопыт",
        "source": "PHB",
        "description_ru": "Охотник и разведчик, сочетающий боевые навыки, выживание и ограниченную природную магию.",
        "hit_die": 10,
        "primary_abilities": ["dex", "wis"],
        "saving_throws": ["str", "dex"],
        "proficiencies": {
            "armor": ["light", "medium", "shields"],
            "weapons": ["simple", "martial"],
            "tools": [],
            "skills_choose": {
                "count": 3,
                "from": ["animal_handling", "athletics", "insight", "investigation", "nature", "perception", "stealth", "survival"],
            },
        },
        "skill_choices": {},
        "starting_equipment": [
            {
                "key": "phb_ranger_starting_equipment",
                "name_ru": "Стартовое снаряжение следопыта",
                "summary_ru": "а) чешуйчатый доспех или б) кожаный доспех; а) два коротких меча или б) два простых рукопашных оружия; а) набор исследователя подземелий или б) набор путешественника; длинный лук и колчан с 20 стрелами.",
            }
        ],
        "features_by_level": {
            1: [
                {"key": "favored_enemy", "name_ru": "Избранный враг", "summary_ru": "Специализируется на борьбе с выбранными типами врагов.", "mechanics": {}},
                {"key": "natural_explorer", "name_ru": "Исследователь природы", "summary_ru": "Лучше путешествует и выживает в избранной местности.", "mechanics": {}},
            ],
            2: [
                {"key": "fighting_style", "name_ru": "Стиль боя", "summary_ru": "Выбор боевого стиля следопыта.", "mechanics": {}},
                {
                    "key": "spellcasting",
                    "name_ru": "Использование заклинаний",
                    "summary_ru": "Следопыт знает ограниченное число заклинаний и использует Мудрость как базовую характеристику.",
                    "mechanics": {
                        "type": "spellcasting",
                        "ability": "wis",
                        "progression": "half",
                        "known_style": "known",
                        "spell_list_key": "ranger",
                    },
                },
            ],
            3: [
                {"key": "ranger_archetype", "name_ru": "Архетип следопыта", "summary_ru": "Выбор подкласса следопыта.", "mechanics": {"type": "subclass_choice"}},
                {"key": "primeval_awareness", "name_ru": "Первобытная осведомлённость", "summary_ru": "Чувствует присутствие особых существ через природную связь.", "mechanics": {}},
            ],
            4: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            5: [{"key": "extra_attack", "name_ru": "Дополнительная атака", "summary_ru": "Совершает больше атак действием.", "mechanics": {}}],
            6: [
                {"key": "favored_enemy_2", "name_ru": "Избранный враг (2)", "summary_ru": "Выбирает ещё одного избранного врага и усиливает прежних.", "mechanics": {}},
                {"key": "natural_explorer_2", "name_ru": "Исследователь природы (2)", "summary_ru": "Выбирает ещё один тип местности.", "mechanics": {}},
            ],
            7: [{"key": "archetype_feature_7", "name_ru": "Умение архетипа (7)", "summary_ru": "Особенность выбранного архетипа на 7 уровне.", "mechanics": {}}],
            8: [
                {"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}},
                {"key": "lands_stride", "name_ru": "Шаг земли", "summary_ru": "Легче проходит через сложную природную местность.", "mechanics": {}},
            ],
            10: [
                {"key": "natural_explorer_3", "name_ru": "Исследователь природы (3)", "summary_ru": "Выбирает третью любимую местность.", "mechanics": {}},
                {"key": "hide_in_plain_sight", "name_ru": "Скрытность на виду", "summary_ru": "Может особенно хорошо сливаться с окружением.", "mechanics": {}},
            ],
            11: [{"key": "archetype_feature_11", "name_ru": "Умение архетипа (11)", "summary_ru": "Особенность выбранного архетипа на 11 уровне.", "mechanics": {}}],
            12: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            14: [{"key": "vanish", "name_ru": "Исчезновение", "summary_ru": "Может быстро прятаться и сложнее отслеживается.", "mechanics": {}}],
            15: [{"key": "archetype_feature_15", "name_ru": "Умение архетипа (15)", "summary_ru": "Высшая особенность выбранного архетипа.", "mechanics": {}}],
            16: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            18: [{"key": "feral_senses", "name_ru": "Первобытные чувства", "summary_ru": "Чувствует скрытых врагов вокруг себя.", "mechanics": {}}],
            19: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            20: [{"key": "foe_slayer", "name_ru": "Убийца врагов", "summary_ru": "Добавляет Мудрость к атаке или урону против избранных врагов.", "mechanics": {}}],
        },
        "subclasses": [
            {"key": "hunter", "name_ru": "Охотник", "features_by_level": {}},
            {"key": "beast_master", "name_ru": "Повелитель зверей", "features_by_level": {}},
        ],
        "spellcasting": {
            "type": "half_caster_known",
            "ability": "wis",
            "spell_list_key": "ranger",
        },
        "spell_lists": {"class": "ranger"},
        "tags": [],
    },
    {
        "key": "rogue",
        "name": "Rogue",
        "name_ru": "Плут",
        "source": "PHB",
        "description_ru": "Ловкий специалист по скрытности, обману и точечным ударам в уязвимые места.",
        "hit_die": 8,
        "primary_abilities": ["dex"],
        "saving_throws": ["dex", "int"],
        "proficiencies": {
            "armor": ["light"],
            "weapons": ["simple", "hand_crossbow", "longsword", "rapier", "shortsword"],
            "tools": ["thieves_tools"],
            "skills_choose": {
                "count": 4,
                "from": [
                    "acrobatics",
                    "athletics",
                    "deception",
                    "insight",
                    "intimidation",
                    "investigation",
                    "perception",
                    "performance",
                    "persuasion",
                    "sleight_of_hand",
                    "stealth",
                ],
            },
        },
        "skill_choices": {},
        "starting_equipment": [
            {
                "key": "phb_rogue_starting_equipment",
                "name_ru": "Стартовое снаряжение плута",
                "summary_ru": "а) рапира или б) короткий меч; а) короткий лук и колчан с 20 стрелами или б) короткий меч; а) набор взломщика, б) набор исследователя подземелий или в) набор путешественника; кожаный доспех, два кинжала и воровские инструменты.",
            }
        ],
        "features_by_level": {
            1: [
                {"key": "expertise", "name_ru": "Компетентность", "summary_ru": "Удваивает бонус мастерства для выбранных навыков или инструментов.", "mechanics": {}},
                {"key": "sneak_attack", "name_ru": "Скрытая атака", "summary_ru": "Наносит дополнительный урон, используя уязвимость врага.", "mechanics": {}},
                {"key": "thieves_cant", "name_ru": "Воровской жаргон", "summary_ru": "Знает тайный язык преступного мира.", "mechanics": {}},
            ],
            2: [{"key": "cunning_action", "name_ru": "Хитрое действие", "summary_ru": "Бонусным действием может рывком, отходить или прятаться.", "mechanics": {}}],
            3: [{"key": "roguish_archetype", "name_ru": "Архетип плута", "summary_ru": "Выбор подкласса плута.", "mechanics": {"type": "subclass_choice"}}],
            4: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            5: [{"key": "uncanny_dodge", "name_ru": "Невероятное уклонение", "summary_ru": "Может уменьшить урон от одной атаки.", "mechanics": {}}],
            6: [{"key": "expertise_2", "name_ru": "Компетентность", "summary_ru": "Получает ещё два случая удвоенного мастерства.", "mechanics": {}}],
            7: [{"key": "evasion", "name_ru": "Уклонение", "summary_ru": "Лучше избегает урона от областных эффектов.", "mechanics": {}}],
            8: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            9: [{"key": "archetype_feature_9", "name_ru": "Умение архетипа (9)", "summary_ru": "Особенность выбранного архетипа на 9 уровне.", "mechanics": {}}],
            10: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            11: [{"key": "reliable_talent", "name_ru": "Надёжный талант", "summary_ru": "Почти не проваливает проверки освоенных навыков.", "mechanics": {}}],
            12: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            13: [{"key": "archetype_feature_13", "name_ru": "Умение архетипа (13)", "summary_ru": "Особенность выбранного архетипа на 13 уровне.", "mechanics": {}}],
            14: [{"key": "blindsense", "name_ru": "Слепое чутьё", "summary_ru": "Чувствует скрытых врагов рядом.", "mechanics": {}}],
            15: [{"key": "slippery_mind", "name_ru": "Скользкий ум", "summary_ru": "Получает мастерство в спасбросках Мудрости.", "mechanics": {}}],
            16: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            17: [{"key": "archetype_feature_17", "name_ru": "Умение архетипа (17)", "summary_ru": "Высшая особенность выбранного архетипа.", "mechanics": {}}],
            18: [{"key": "elusive", "name_ru": "Неуловимый", "summary_ru": "Противнику труднее поймать плута врасплох.", "mechanics": {}}],
            19: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            20: [{"key": "stroke_of_luck", "name_ru": "Удача героя", "summary_ru": "Может обратить провал в успех в критический момент.", "mechanics": {}}],
        },
        "subclasses": [
            {"key": "thief", "name_ru": "Вор", "features_by_level": {}},
            {"key": "assassin", "name_ru": "Убийца", "features_by_level": {}},
            {"key": "arcane_trickster", "name_ru": "Мистический ловкач", "features_by_level": {}},
        ],
        "spellcasting": {},
        "spell_lists": {},
        "tags": [],
    },
    {
        "key": "sorcerer",
        "name": "Sorcerer",
        "name_ru": "Чародей",
        "source": "PHB",
        "description_ru": "Природный носитель магии, преобразующий врождённую силу через происхождение и метамагию.",
        "hit_die": 6,
        "primary_abilities": ["cha"],
        "saving_throws": ["con", "cha"],
        "proficiencies": {
            "armor": [],
            "weapons": ["dagger", "dart", "sling", "quarterstaff", "light_crossbow"],
            "tools": [],
            "skills_choose": {
                "count": 2,
                "from": ["arcana", "deception", "insight", "intimidation", "persuasion", "religion"],
            },
        },
        "skill_choices": {},
        "starting_equipment": [
            {
                "key": "phb_sorcerer_starting_equipment",
                "name_ru": "Стартовое снаряжение чародея",
                "summary_ru": "а) лёгкий арбалет и 20 болтов или б) любое простое оружие; а) мешочек с компонентами или б) магическая фокусировка; а) набор исследователя подземелий или б) набор путешественника; два кинжала.",
            }
        ],
        "features_by_level": {
            1: [
                {
                    "key": "spellcasting",
                    "name_ru": "Использование заклинаний",
                    "summary_ru": "Чародей знает ограниченное число заклинаний и использует Харизму как базовую характеристику.",
                    "mechanics": {
                        "type": "spellcasting",
                        "ability": "cha",
                        "progression": "full",
                        "known_style": "known",
                        "spell_list_key": "sorcerer",
                    },
                },
                {"key": "sorcerous_origin", "name_ru": "Источник магии", "summary_ru": "Выбор подкласса чародея.", "mechanics": {"type": "subclass_choice"}},
            ],
            2: [{"key": "font_of_magic", "name_ru": "Источник магии", "summary_ru": "Получает очки чародейства для преобразования силы и ячеек.", "mechanics": {}}],
            3: [{"key": "metamagic", "name_ru": "Метамагия", "summary_ru": "Меняет способ действия заклинаний особыми приёмами.", "mechanics": {}}],
            4: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            6: [{"key": "origin_feature_6", "name_ru": "Умение происхождения (6)", "summary_ru": "Особенность выбранного магического происхождения.", "mechanics": {}}],
            8: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            10: [{"key": "metamagic_2", "name_ru": "Метамагия (2)", "summary_ru": "Осваивает дополнительные варианты метамагии.", "mechanics": {}}],
            12: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            14: [{"key": "origin_feature_14", "name_ru": "Умение происхождения (14)", "summary_ru": "Особенность выбранного происхождения на 14 уровне.", "mechanics": {}}],
            16: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            17: [{"key": "metamagic_3", "name_ru": "Метамагия (3)", "summary_ru": "Осваивает ещё одну форму метамагии.", "mechanics": {}}],
            18: [{"key": "origin_feature_18", "name_ru": "Умение происхождения (18)", "summary_ru": "Высшая особенность выбранного происхождения.", "mechanics": {}}],
            19: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            20: [{"key": "sorcerous_restoration", "name_ru": "Восстановление чародейства", "summary_ru": "Короткий отдых возвращает часть очков чародейства.", "mechanics": {}}],
        },
        "subclasses": [
            {"key": "draconic_bloodline", "name_ru": "Наследие дракона", "features_by_level": {}},
            {"key": "wild_magic", "name_ru": "Дикая магия", "features_by_level": {}},
        ],
        "spellcasting": {
            "type": "full_caster_known",
            "ability": "cha",
            "spell_list_key": "sorcerer",
        },
        "spell_lists": {"class": "sorcerer"},
        "tags": [],
    },
    {
        "key": "warlock",
        "name": "Warlock",
        "name_ru": "Колдун",
        "source": "PHB",
        "description_ru": "Заклинатель договора, получающий силу от потустороннего покровителя и тайных воззваний.",
        "hit_die": 8,
        "primary_abilities": ["cha"],
        "saving_throws": ["wis", "cha"],
        "proficiencies": {
            "armor": ["light"],
            "weapons": ["simple"],
            "tools": [],
            "skills_choose": {
                "count": 2,
                "from": ["arcana", "deception", "history", "intimidation", "investigation", "nature", "religion"],
            },
        },
        "skill_choices": {},
        "starting_equipment": [
            {
                "key": "phb_warlock_starting_equipment",
                "name_ru": "Стартовое снаряжение колдуна",
                "summary_ru": "а) лёгкий арбалет и 20 болтов или б) любое простое оружие; а) мешочек с компонентами или б) магическая фокусировка; а) набор учёного или б) набор исследователя подземелий; кожаный доспех, любое простое оружие и два кинжала.",
            }
        ],
        "features_by_level": {
            1: [
                {"key": "otherworldly_patron", "name_ru": "Потусторонний покровитель", "summary_ru": "Выбор подкласса колдуна.", "mechanics": {"type": "subclass_choice"}},
                {
                    "key": "pact_magic",
                    "name_ru": "Магия договора",
                    "summary_ru": "Колдун использует особые ячейки договора и Харизму как базовую характеристику.",
                    "mechanics": {
                        "type": "spellcasting",
                        "ability": "cha",
                        "progression": "pact",
                        "known_style": "known",
                        "spell_list_key": "warlock",
                    },
                },
            ],
            2: [{"key": "eldritch_invocations", "name_ru": "Таинственные воззвания", "summary_ru": "Осваивает постоянные магические приёмы и улучшения.", "mechanics": {}}],
            3: [{"key": "pact_boon", "name_ru": "Предмет договора", "summary_ru": "Получает особый дар договора от покровителя.", "mechanics": {}}],
            4: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            6: [{"key": "patron_feature_6", "name_ru": "Умение покровителя (6)", "summary_ru": "Особенность выбранного покровителя на 6 уровне.", "mechanics": {}}],
            8: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            10: [{"key": "patron_feature_10", "name_ru": "Умение покровителя (10)", "summary_ru": "Особенность выбранного покровителя на 10 уровне.", "mechanics": {}}],
            11: [{"key": "mystic_arcanum_6", "name_ru": "Мистический арканум (6)", "summary_ru": "Получает одно великое заклинание 6 круга.", "mechanics": {}}],
            12: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            13: [{"key": "mystic_arcanum_7", "name_ru": "Мистический арканум (7)", "summary_ru": "Получает одно великое заклинание 7 круга.", "mechanics": {}}],
            14: [{"key": "patron_feature_14", "name_ru": "Умение покровителя (14)", "summary_ru": "Высшая особенность выбранного покровителя.", "mechanics": {}}],
            15: [{"key": "mystic_arcanum_8", "name_ru": "Мистический арканум (8)", "summary_ru": "Получает одно великое заклинание 8 круга.", "mechanics": {}}],
            16: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            17: [{"key": "mystic_arcanum_9", "name_ru": "Мистический арканум (9)", "summary_ru": "Получает одно великое заклинание 9 круга.", "mechanics": {}}],
            19: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            20: [{"key": "eldritch_master", "name_ru": "Таинственный мастер", "summary_ru": "Быстро восстанавливает ячейки договора после короткой медитации.", "mechanics": {}}],
        },
        "subclasses": [
            {"key": "archfey", "name_ru": "Архифея", "features_by_level": {}},
            {"key": "fiend", "name_ru": "Исчадие", "features_by_level": {}},
            {"key": "great_old_one", "name_ru": "Великий Древний", "features_by_level": {}},
        ],
        "spellcasting": {
            "type": "pact_magic",
            "ability": "cha",
            "spell_list_key": "warlock",
        },
        "spell_lists": {"class": "warlock"},
        "tags": [],
    },
    {
        "key": "wizard",
        "name": "Wizard",
        "name_ru": "Волшебник",
        "source": "PHB",
        "description_ru": "Учёный заклинатель, собирающий магию через книгу заклинаний и школы волшебства.",
        "hit_die": 6,
        "primary_abilities": ["int"],
        "saving_throws": ["int", "wis"],
        "proficiencies": {
            "armor": [],
            "weapons": ["dagger", "dart", "sling", "quarterstaff", "light_crossbow"],
            "tools": [],
            "skills_choose": {
                "count": 2,
                "from": ["arcana", "history", "insight", "investigation", "medicine", "religion"],
            },
        },
        "skill_choices": {},
        "starting_equipment": [
            {
                "key": "phb_wizard_starting_equipment",
                "name_ru": "Стартовое снаряжение волшебника",
                "summary_ru": "а) боевой посох или б) кинжал; а) мешочек с компонентами или б) магическая фокусировка; а) набор учёного или б) набор путешественника; книга заклинаний.",
            }
        ],
        "features_by_level": {
            1: [
                {
                    "key": "spellcasting",
                    "name_ru": "Использование заклинаний",
                    "summary_ru": "Волшебник ведёт книгу заклинаний, готовит чары и использует Интеллект как базовую характеристику.",
                    "mechanics": {
                        "type": "spellcasting",
                        "ability": "int",
                        "progression": "full",
                        "known_style": "spellbook_prepared",
                        "ritual": True,
                        "spell_list_key": "wizard",
                    },
                },
                {"key": "arcane_recovery", "name_ru": "Магическое восстановление", "summary_ru": "Частично восстанавливает ячейки после короткого отдыха.", "mechanics": {}},
            ],
            2: [{"key": "arcane_tradition", "name_ru": "Магическая традиция", "summary_ru": "Выбор школы волшебства.", "mechanics": {"type": "subclass_choice"}}],
            4: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            6: [{"key": "tradition_feature_6", "name_ru": "Умение традиции (6)", "summary_ru": "Особенность выбранной школы на 6 уровне.", "mechanics": {}}],
            8: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            10: [{"key": "tradition_feature_10", "name_ru": "Умение традиции (10)", "summary_ru": "Особенность выбранной школы на 10 уровне.", "mechanics": {}}],
            12: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            14: [{"key": "tradition_feature_14", "name_ru": "Умение традиции (14)", "summary_ru": "Высшая особенность выбранной школы волшебства.", "mechanics": {}}],
            16: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            18: [{"key": "spell_mastery", "name_ru": "Мастерство заклинателя", "summary_ru": "Может свободно накладывать часть известных чар низкого круга.", "mechanics": {}}],
            19: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            20: [{"key": "signature_spells", "name_ru": "Фирменные заклинания", "summary_ru": "Выбирает особые заклинания, к которым обращается чаще всего.", "mechanics": {}}],
        },
        "subclasses": [
            {"key": "abjuration", "name_ru": "Школа Ограждения", "features_by_level": {}},
            {"key": "conjuration", "name_ru": "Школа Вызова", "features_by_level": {}},
            {"key": "divination", "name_ru": "Школа Прорицания", "features_by_level": {}},
            {"key": "enchantment", "name_ru": "Школа Очарования", "features_by_level": {}},
            {"key": "evocation", "name_ru": "Школа Воплощения", "features_by_level": {}},
            {"key": "illusion", "name_ru": "Школа Иллюзии", "features_by_level": {}},
            {"key": "necromancy", "name_ru": "Школа Некромантии", "features_by_level": {}},
            {"key": "transmutation", "name_ru": "Школа Преобразования", "features_by_level": {}},
        ],
        "spellcasting": {
            "type": "full_caster_prepared_spellbook",
            "ability": "int",
            "ritual": True,
            "spell_list_key": "wizard",
        },
        "spell_lists": {"class": "wizard"},
        "tags": [],
    },
    {
        "key": "artificer",
        "name": "Artificer",
        "name_ru": "Изобретатель",
        "source": "TCE",
        "description_ru": "Магический ремесленник, сочетающий изобретательность, инструменты и подготовленную магию предметов.",
        "hit_die": 8,
        "primary_abilities": ["int"],
        "saving_throws": ["con", "int"],
        "proficiencies": {
            "armor": ["light", "medium", "shields"],
            "weapons": ["simple"],
            "tools": ["thieves_tools", "tinkers_tools"],
            "tools_choose": {"count": 1, "from": ["artisan_tools"]},
            "skills_choose": {
                "count": 2,
                "from": ["arcana", "history", "investigation", "medicine", "nature", "perception", "sleight_of_hand"],
            },
        },
        "skill_choices": {},
        "starting_equipment": [
            {
                "key": "tce_artificer_starting_equipment",
                "name_ru": "Стартовое снаряжение изобретателя",
                "summary_ru": "Любые два простых оружия; лёгкий арбалет и 20 болтов; а) стёганый доспех или б) кожаный доспех; воровские инструменты и набор ремесленных инструментов на выбор; набор исследователя подземелий.",
            }
        ],
        "features_by_level": {
            1: [
                {
                    "key": "magical_tinkering",
                    "name_ru": "Магическое ремесло",
                    "summary_ru": "Наполняет крошечные предметы простыми магическими эффектами для света, звука, записи или запаха.",
                    "mechanics": {},
                },
                {
                    "key": "spellcasting",
                    "name_ru": "Использование заклинаний",
                    "summary_ru": "Изобретатель подготавливает заклинания из списка artificer и использует Интеллект как базовую характеристику.",
                    "mechanics": {
                        "type": "spellcasting",
                        "ability": "int",
                        "progression": "half",
                        "known_style": "prepared",
                        "focus": ["thieves_tools", "artisan_tools"],
                        "ritual": True,
                        "spell_list_key": "artificer",
                    },
                },
            ],
            2: [
                {"key": "infuse_item", "name_ru": "Инфузия предмета", "summary_ru": "Создаёт магические инфузии и временно наделяет ими предметы.", "mechanics": {}},
            ],
            3: [
                {"key": "artificer_specialist", "name_ru": "Специалист-изобретатель", "summary_ru": "Выбор подкласса изобретателя.", "mechanics": {"type": "subclass_choice"}},
                {"key": "the_right_tool_for_the_job", "name_ru": "Нужный инструмент для дела", "summary_ru": "Может быстро создать требуемый набор ремесленных инструментов.", "mechanics": {}},
            ],
            4: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            5: [{"key": "specialist_feature_5", "name_ru": "Умение специалиста (5)", "summary_ru": "Особенность выбранной специализации на 5 уровне.", "mechanics": {}}],
            6: [{"key": "tool_expertise", "name_ru": "Мастерство инструментов", "summary_ru": "Удваивает бонус мастерства для проверок инструментами, которыми владеет.", "mechanics": {}}],
            7: [{"key": "flash_of_genius", "name_ru": "Вспышка гениальности", "summary_ru": "Реакцией добавляет Интеллект к проверке или спасброску союзника либо своему.", "mechanics": {}}],
            8: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            9: [{"key": "specialist_feature_9", "name_ru": "Умение специалиста (9)", "summary_ru": "Особенность выбранной специализации на 9 уровне.", "mechanics": {}}],
            10: [
                {"key": "magic_item_adept", "name_ru": "Адепт магических предметов", "summary_ru": "Лучше настраивается на магические предметы и быстрее создаёт обычные магические вещи.", "mechanics": {}},
                {"key": "infused_item_improvement", "name_ru": "Улучшенные инфузии", "summary_ru": "Может поддерживать больше инфузий и знает более сильные варианты.", "mechanics": {}},
            ],
            11: [{"key": "spell_storing_item", "name_ru": "Предмет-хранилище заклинания", "summary_ru": "Закрепляет известное заклинание в предмете для многократного применения.", "mechanics": {}}],
            12: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            14: [{"key": "magic_item_savant", "name_ru": "Знаток магических предметов", "summary_ru": "Игнорирует часть требований к магическим предметам и настраивается на большее число вещей.", "mechanics": {}}],
            15: [{"key": "specialist_feature_15", "name_ru": "Умение специалиста (15)", "summary_ru": "Продвинутая особенность выбранной специализации.", "mechanics": {}}],
            16: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            18: [{"key": "magic_item_master", "name_ru": "Мастер магических предметов", "summary_ru": "Может одновременно настроиться на ещё большее число магических предметов.", "mechanics": {}}],
            19: [{"key": "asi", "name_ru": "Увеличение характеристик", "summary_ru": "Улучшение характеристик или выбор таланта.", "mechanics": {}}],
            20: [{"key": "soul_of_artifice", "name_ru": "Душа изобретения", "summary_ru": "Пиковая связь с магическими предметами усиливает спасброски и позволяет удержаться на грани поражения.", "mechanics": {}}],
        },
        "subclasses": [
            {"key": "alchemist", "name_ru": "Алхимик", "features_by_level": {}},
            {"key": "armorer", "name_ru": "Бронник", "features_by_level": {}},
            {"key": "artillerist", "name_ru": "Артиллерист", "features_by_level": {}},
            {"key": "battle_smith", "name_ru": "Боевой кузнец", "features_by_level": {}},
        ],
        "spellcasting": {
            "type": "half_caster_prepared",
            "ability": "int",
            "focus": ["thieves_tools", "artisan_tools"],
            "ritual": True,
            "spell_list_key": "artificer",
        },
        "spell_lists": {"class": "artificer"},
        "tags": [],
    },
    {
        "key": "mage",
        "name": "Mage",
        "name_ru": "Маг",
        "source": "legacy",
        "description_ru": "Legacy-запись для обратной совместимости старого ключа класса; в актуальном каталоге должна резолвиться как wizard.",
        "hit_die": 6,
        "primary_abilities": ["int"],
        "saving_throws": ["int", "wis"],
        "proficiencies": {
            "armor": [],
            "weapons": ["dagger", "dart", "sling", "quarterstaff", "light_crossbow"],
            "tools": [],
            "skills_choose": {
                "count": 2,
                "from": ["arcana", "history", "insight", "investigation", "medicine", "religion"],
            },
        },
        "skill_choices": {},
        "starting_equipment": [],
        "features_by_level": {},
        "subclasses": [],
        "spellcasting": {
            "type": "full_caster_prepared_spellbook",
            "ability": "int",
            "ritual": True,
            "spell_list_key": "wizard",
            "legacy_alias_for": "wizard",
        },
        "spell_lists": {"class": "wizard"},
        "tags": ["legacy", "alias_for_wizard", "not_for_new_characters"],
    },
]
