from __future__ import annotations

from typing import Any

# Auto-generated from external resources via scripts/import_races_from_html.py
IMPORTED_RACE_CATALOG: list[dict[str, Any]] = [{'key': 'autognome',
  'name_ru': 'Автогном',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'bugbear',
  'name_ru': 'Багбир',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'centaur',
  'name_ru': 'Кентавр',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'changeling',
  'name_ru': 'Чейнджлинг',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'custom_lineage',
  'name_ru': 'Своё происхождение',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'dhampir',
  'name_ru': 'Дампир',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'fairy',
  'name_ru': 'Фэйри',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'firbolg',
  'name_ru': 'Фирболг',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'gith',
  'name_ru': 'Гит',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'goblin',
  'name_ru': 'Гоблин',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'grung',
  'name_ru': 'Грунг',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'harengon',
  'name_ru': 'Зайцегон',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'hexblood',
  'name_ru': 'Ведьмовская кровь',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'hobgoblin',
  'name_ru': 'Хобгоблин',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'kalashtar',
  'name_ru': 'Калаштар',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'kender',
  'name_ru': 'Кендер',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'kenku',
  'name_ru': 'Кенку',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'kobold',
  'name_ru': 'Кобольд',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'leonin',
  'name_ru': 'Леонин',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'lizardfolk',
  'name_ru': 'Людоящер',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'locathah',
  'name_ru': 'Локата',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'loxodon',
  'name_ru': 'Локсодон',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'minotaur',
  'name_ru': 'Минотавр',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'orc',
  'name_ru': 'Орк',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'owlin',
  'name_ru': 'Совлин',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'reborn',
  'name_ru': 'Возрождённый',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'satyr',
  'name_ru': 'Сатир',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'shifter',
  'name_ru': 'Шифтер',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'simic_hybrid',
  'name_ru': 'Гибрид Симиков',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'tabaxi',
  'name_ru': 'Табакси',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'tortle',
  'name_ru': 'Тортл',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'triton',
  'name_ru': 'Тритон',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'warforged',
  'name_ru': 'Кованый',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'},
 {'key': 'yuan_ti_pureblood',
  'name_ru': 'Юань-ти',
  'description_ru': '',
  'asi': [],
  'age': {},
  'alignment': '',
  'size': 'medium',
  'speed_ft': 30,
  'speed_notes_ru': '',
  'languages': ['common'],
  'traits': [],
  'subraces': [],
  'source': 'external resources',
  'tags': [],
  'notes_ru': 'Импортировано из внешнего источника, требует проверки мастером'}]
