"""turn timer

Revision ID: 80a1bf5d3ec6
Revises: 85c675229962
Create Date: 2026-02-16 14:10:41.790049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a1bf5d3ec6'
down_revision: Union[str, Sequence[str], None] = '85c675229962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('sessions', sa.Column('turn_started_at', sa.DateTime(), nullable=True))

    op.add_column(
        'sessions',
        sa.Column('is_paused', sa.Boolean(), nullable=False, server_default=sa.false())
    )

    # убрать дефолт на уровне БД, чтобы он не висел навсегда
    op.alter_column('sessions', 'is_paused', server_default=None)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'is_paused')
    op.drop_column('sessions', 'turn_started_at')
    # ### end Alembic commands ###
