"""Add web_user_id and make telegram_user_id nullable

Revision ID: 81f0f0157862
Revises: 80a1bf5d3ec6
Create Date: 2026-02-17 21:03:49.926648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f0f0157862'
down_revision: Union[str, Sequence[str], None] = '80a1bf5d3ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('web_user_id', sa.BigInteger(), nullable=True))
    op.execute("UPDATE players SET web_user_id = telegram_user_id WHERE web_user_id IS NULL")
    op.alter_column('players', 'telegram_user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index(op.f('ix_players_web_user_id'), 'players', ['web_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_web_user_id'), table_name='players')
    op.alter_column('players', 'telegram_user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('players', 'web_user_id')
    # ### end Alembic commands ###
